(* Regression suite for src/corrected/StradFixed2.wl (context RadicalDenest2`).

   Groups:  R4-* translate tests/Regression.wlt of review-4,
            R5-* translate tests/regression.wlt of review-5,
            R6-* translate tests/StradImproved.wlt of review-6,
            G-*  are the fifteen inputs of src/corrected/KNOWN_GAPS.md,
            A-*  are contracts kept from the unified-A battery.
   Options and report keys of the reviews' proposals were mapped onto those of
   StradFixed2 (see unified-B, Section "Translating the reviews' test suites").
   Run with tests/run_tests.wls in a fresh kernel. *)

Begin["RadicalDenest2Tests`"];
ClearAll[d, eq, depth, improves, x, y, f, h];
d[e_, opts___] := RadicalDenest2`Strad[e, opts];
eq[a_, b_] := TrueQ[RootReduce[a - b] === 0];
depth[e_] := RadicalDenest2`RadicalDepth[e];
improves[e_, target_, opts___] := Module[{v = d[e, opts]}, eq[v, target] && depth[v] < depth[e]];

(* ---------------- R4: review-4, tests/Regression.wlt ---------------- *)
VerificationTest[RadicalDenest2`CertifiedEqualQ[Sqrt[5 + 2 Sqrt[6]], Sqrt[2] + Sqrt[3]], True, TestID -> "R4-exact-equality-positive"]
VerificationTest[RadicalDenest2`CertifiedEqualQ[Sqrt[3 - 2 Sqrt[2]], 1 - Sqrt[2]], False, TestID -> "R4-reject-wrong-square-root-branch"]
VerificationTest[RadicalDenest2`CertifiedEqualQ[Sqrt[2], Sqrt[2] + 10^-100], False, TestID -> "R4-no-numerical-tolerance-acceptance"]
VerificationTest[RadicalDenest2`CertifiedEqualQ[x, x], False, TestID -> "R4-symbolic-equality-is-not-algebraic-certificate"]
VerificationTest[{RadicalDenest2`ExactAlgebraicQ[Pi], RadicalDenest2`ExactAlgebraicQ[N[Sqrt[2]]], RadicalDenest2`ExactAlgebraicQ[(1 + I)/2]}, {False, False, True}, TestID -> "R4-supported-exact-domain"]
VerificationTest[Block[{RadicalDenest2`Private`$cfg = Association[Options[RadicalDenest2`Strad]]}, RadicalDenest2`Private`validPolynomialQ[$Failed, x]], False, TestID -> "R4-failed-is-not-an-accepted-polynomial"]
VerificationTest[Block[{RadicalDenest2`Private`$cfg = Association[Options[RadicalDenest2`Strad]]}, RadicalDenest2`Private`validPolynomialQ[7, x]], False, TestID -> "R4-constant-is-not-a-minimal-polynomial"]
VerificationTest[RadicalDenest2`RadicalDepth[Root[#^5 - # - 1 &, 1]], 0, TestID -> "R4-root-payload-is-opaque"]
VerificationTest[First[RadicalDenest2`RadicalCost[Root[#^5 - # - 1 &, 1]]], 1, TestID -> "R4-root-representation-is-not-free"]
VerificationTest[RadicalDenest2`RadicalCost[{}], {0, 0, 0, LeafCount[{}], 0}, TestID -> "R4-empty-list-metrics"]
VerificationTest[improves[Sqrt[5 + 2 Sqrt[6]], Sqrt[2] + Sqrt[3]], True, TestID -> "R4-direct-quadratic-denesting"]
VerificationTest[improves[Sqrt[3 - 2 Sqrt[2]], Sqrt[2] - 1], True, TestID -> "R4-negative-coefficient-positive-root"]
VerificationTest[improves[Sqrt[4 + 3 Sqrt[2]], 2^(1/4) (1 + Sqrt[2])], True, TestID -> "R4-indirect-fourth-root-minus-sign"]
VerificationTest[improves[Sqrt[-4 + 3 Sqrt[2]], 2^(1/4) (Sqrt[2] - 1)], True, TestID -> "R4-indirect-negative-rational-part"]
VerificationTest[eq[d[Sqrt[-3 - 2 Sqrt[2]]], I (1 + Sqrt[2])], True, TestID -> "R4-negative-radicand-principal-square-root"]
VerificationTest[improves[(49 + 20 Sqrt[6])^(1/4), Sqrt[2] + Sqrt[3], True], True, TestID -> "R4-composite-index-without-cost-neutral-stall"]
VerificationTest[eq[d[(3 + 2 Sqrt[2])^(-1/2)], Sqrt[2] - 1], True, TestID -> "R4-negative-rational-exponent"]
VerificationTest[improves[(7 + 5 Sqrt[2])^(1/3), 1 + Sqrt[2]], True, TestID -> "R4-cubic-trace-norm"]
VerificationTest[Module[{e = (7 - 5 Sqrt[2])^(1/3), r}, r = d[e]; eq[r, e] && ! eq[r, 1 - Sqrt[2]]], True, TestID -> "R4-negative-real-cubic-is-not-real-root"]
VerificationTest[improves[Sqrt[5^(1/3) - 4^(1/3)], (2^(1/3) + 20^(1/3) - 25^(1/3))/3], True, TestID -> "R4-honsbeek-ramanujan-square-of-cube-roots"]
VerificationTest[Module[{e = x + Sqrt[5 + 2 Sqrt[6]], r}, r = d[e, "Solver" -> (0 &), "Factor" -> False]; eq[(r - x) - (e - x), 0]], True, TestID -> "R4-untrusted-solver-in-symbolic-host"]
VerificationTest[Module[{e = Sqrt[x^2] + Sqrt[5 + 2 Sqrt[6]], r}, r = Block[{$Assumptions = x > 0}, d[e]]; eq[(r - e) /. x -> -2, 0]], True, TestID -> "R4-ambient-assumptions-do-not-rewrite-host"]
VerificationTest[Module[{e = f[Sqrt[5 + 2 Sqrt[6]]]}, SameQ[d[e], e]], True, TestID -> "R4-unknown-head-is-opaque"]
VerificationTest[SameQ[d[HoldComplete[Sqrt[5 + 2 Sqrt[6]]]], HoldComplete[Sqrt[5 + 2 Sqrt[6]]]], True, TestID -> "R4-held-input-is-opaque"]
VerificationTest[Module[{e = (x + 1) (x - 1)}, SameQ[RadicalDenest2`Factorc[e], e]], True, TestID -> "R4-symbolic-factorc-is-conservative"]
VerificationTest[RadicalDenest2`CertifiedEqualQ[RadicalDenest2`RationalizeDenominator[1/(1 + Sqrt[2])], Sqrt[2] - 1], True, TestID -> "R4-horner-inverse"]
VerificationTest[RadicalDenest2`CertifiedEqualQ[RadicalDenest2`RationalizeDenominator[x/(1 + Sqrt[2])] /. x -> 1, Sqrt[2] - 1], True, TestID -> "R4-symbolic-numerator-local-inverse-certificate"]
VerificationTest[RadicalDenest2`CertifiedEqualQ[Sqrt[I] (-1 + I), -Sqrt[2]], True, TestID -> "R4-aggregate-positive-factor-is-not-termwise-license"]
VerificationTest[Module[{saved = Options[RadicalDenest2`Strad], e = Sqrt[5 + 2 Sqrt[6]], r}, SetOptions[RadicalDenest2`Strad, "TimeBudget" -> 0]; r = d[e]; SetOptions[RadicalDenest2`Strad, Sequence @@ saved]; SameQ[r, e]], True, TestID -> "R4-setoptions-strad-is-effective"]
VerificationTest[Module[{saved = Options[RadicalDenest2`DenestRadicals], e = Sqrt[5 + 2 Sqrt[6]], r}, SetOptions[RadicalDenest2`DenestRadicals, "TimeBudget" -> 0]; r = RadicalDenest2`DenestRadicals[e]; SetOptions[RadicalDenest2`DenestRadicals, Sequence @@ saved]; SameQ[r, e]], True, TestID -> "R4-setoptions-wrapper-is-effective"]
VerificationTest[Module[{r = RadicalDenest2`DenestReport[Sqrt[5 + 2 Sqrt[6]], "TimeBudget" -> 0]}, r["Statistics"]["Trials"] === 0 && MemberQ[r["Limits"], "TimeBudget"] && SameQ[r["Result"], Sqrt[5 + 2 Sqrt[6]]]], True, TestID -> "R4-zero-budget-no-work"]
VerificationTest[And @@ (FailureQ[d[Sqrt[1 + Sqrt[2]], #]] & /@ {"MultiplierCap" -> Infinity, "MultiplierCap" -> -1, "MultiplierCap" -> 1/2, "MaxTrials" -> -1, "TimeBudget" -> Infinity, "TimeBudget" -> -1, "MaxRootIndex" -> 0, "AllLevels" -> "yes", "Bogus" -> 1}), True, TestID -> "R4-invalid-options-fail-explicitly"]
VerificationTest[Module[{r = RadicalDenest2`DenestReport[Sqrt[1 + Sqrt[2]], "Multipliers" -> Range[20], "MultiplierCap" -> 1, "TimeBudget" -> 20]}, r["Statistics"]["MultipliersAdmitted"] <= 1 && r["Statistics"]["Trials"] <= 1], True, TestID -> "R4-forced-list-obeys-cap"]
VerificationTest[Module[{r = RadicalDenest2`DenestReport[{Sqrt[1 + Sqrt[2]], Sqrt[1 + Sqrt[3]]}, "MaxTrials" -> 1, "Multipliers" -> {1}, "TimeBudget" -> 30]}, r["Statistics"]["Trials"] <= 2], True, TestID -> "R4-trial-budget-per-island-across-list"]
VerificationTest[Module[{r = RadicalDenest2`DenestReport[Sqrt[1 + Sqrt[2]], "Trace" -> True, "MaxTraceEntries" -> 1, "MaxTrials" -> 2, "TimeBudget" -> 20]}, Length[r["Trace"]] <= 1], True, TestID -> "R4-bounded-diagnostics"]
VerificationTest[Module[{e = Sqrt[5 + 2 Sqrt[6]], r}, r = d[e, "Solver" -> (Throw["bad", "callback"] &)]; eq[r, e]], True, TestID -> "R4-callback-throw-is-not-a-rewrite"]
VerificationTest[Module[{examples = {Sqrt[2 + Sqrt[3]], Sqrt[4 + 3 Sqrt[2]], (7 - 5 Sqrt[2])^(1/3), (49 + 20 Sqrt[6])^(1/4)}, results}, results = d[examples, True]; And @@ MapThread[(eq[#1, #2] && Order[RadicalDenest2`RadicalCost[#1], RadicalDenest2`RadicalCost[#2]] =!= -1) &, {results, examples}]], True, TestID -> "R4-each-example-equal-and-no-more-expensive"]

(* ---------------- R5: review-5, tests/regression.wlt ---------------- *)
VerificationTest[eq[d[Sqrt[5 + 2 Sqrt[6]]], Sqrt[2] + Sqrt[3]], True, TestID -> "R5-direct-square-value"]
VerificationTest[depth[d[Sqrt[5 + 2 Sqrt[6]]]], 1, TestID -> "R5-direct-square-depth"]
VerificationTest[eq[d[Sqrt[4 + 3 Sqrt[2]]], 2^(1/4) (1 + Sqrt[2])], True, TestID -> "R5-indirect-fourth-root-value"]
VerificationTest[depth[d[Sqrt[4 + 3 Sqrt[2]]]], 1, TestID -> "R5-indirect-fourth-root-depth"]
VerificationTest[eq[d[Sqrt[3 - 2 Sqrt[2]]], Sqrt[2] - 1], True, TestID -> "R5-small-positive-branch"]
VerificationTest[eq[d[Sqrt[-5 - 2 Sqrt[6]]], I (Sqrt[2] + Sqrt[3])], True, TestID -> "R5-negative-radicand-principal-square-root"]
VerificationTest[eq[d[(41 - 29 Sqrt[2])^(1/5)], (41 - 29 Sqrt[2])^(1/5)], True, TestID -> "R5-principal-fifth-power-preserved"]
VerificationTest[RadicalDenest2`CertifiedEqualQ[1 - Sqrt[2], (41 - 29 Sqrt[2])^(1/5)], False, TestID -> "R5-real-fifth-root-is-not-principal-power"]
VerificationTest[Module[{a = Sqrt[5 + 2 Sqrt[6]], r}, r = d[x + a, "Solver" -> Function[z, 0]]; eq[r - x, a]], True, TestID -> "R5-bad-zero-solver-in-symbolic-host-rejected"]
VerificationTest[Module[{a = Sqrt[5 + 2 Sqrt[6]], r}, r = d[x + a, "Solver" -> Function[z, $Failed]]; FreeQ[r, $Failed] && eq[r - x, a]], True, TestID -> "R5-failed-solver-does-not-leak"]
VerificationTest[Module[{a = Sqrt[5 + 2 Sqrt[6]], r}, r = d[x + a, "Solver" -> Function[z, 1.41421356237]]; FreeQ[r, _Real] && eq[r - x, a]], True, TestID -> "R5-approximate-solver-does-not-leak"]
VerificationTest[Block[{$Assumptions = x > 0}, SameQ[d[Sqrt[x^2]], Sqrt[x^2]]], True, TestID -> "R5-ambient-assumptions-do-not-rewrite-host"]
VerificationTest[SameQ[d[h[Sqrt[5 + 2 Sqrt[6]]]], h[Sqrt[5 + 2 Sqrt[6]]]], True, TestID -> "R5-unknown-head-is-opaque"]
VerificationTest[RadicalDenest2`ExactAlgebraicQ[Pi], False, TestID -> "R5-transcendental-constant-rejected"]
VerificationTest[RadicalDenest2`ExactAlgebraicQ[Sqrt[2] + 3^(1/3)], True, TestID -> "R5-explicit-algebraic-grammar"]
VerificationTest[RadicalDenest2`EqualityStatus[Sqrt[2], -Sqrt[2]], "Different", TestID -> "R5-conjugates-distinguished"]
VerificationTest[RadicalDenest2`EqualityStatus[Sqrt[2], x], "Unknown", TestID -> "R5-non-algebraic-comparison-is-unknown"]
VerificationTest[Module[{a = Sqrt[5 + 2 Sqrt[6]], r}, r = RadicalDenest2`DenestReport[a, {"TimeBudget" -> 0}]; {r["Result"] === a, r["Statistics"]["Trials"], r["Status"]}], {True, 0, "Disabled"}, TestID -> "R5-zero-total-budget-is-noop"]
VerificationTest[FailureQ[RadicalDenest2`DenestReport[Sqrt[5 + 2 Sqrt[6]], "MaxTrials" -> -1]], True, TestID -> "R5-invalid-integer-option"]
VerificationTest[FailureQ[RadicalDenest2`DenestReport[Sqrt[5 + 2 Sqrt[6]], "TimeBudget" -> "bad"]], True, TestID -> "R5-invalid-time-option"]
VerificationTest[FailureQ[RadicalDenest2`DenestReport[Sqrt[5 + 2 Sqrt[6]], "UnknownOption" -> 1]], True, TestID -> "R5-unknown-option-rejected"]
VerificationTest[Module[{defaults = Options[RadicalDenest2`Strad], a = Sqrt[5 + 2 Sqrt[6]], result}, SetOptions[RadicalDenest2`Strad, "TimeBudget" -> 0]; result = d[a]; SetOptions[RadicalDenest2`Strad, Sequence @@ defaults]; SameQ[result, a]], True, TestID -> "R5-SetOptions-on-alias-is-honored"]
VerificationTest[Module[{a = Sqrt[5 + 2 Sqrt[6]], r}, r = RadicalDenest2`DenestReport[a, "MaxTrials" -> 0]; r["Statistics"]["Trials"] === 0 && eq[r["Result"], a] && depth[r["Result"]] === 1], True, TestID -> "R5-zero-trials-disables-only-multiplier-search"]
VerificationTest[Module[{r = RadicalDenest2`DenestReport[{Sqrt[2 + Sqrt[2]], Sqrt[3 + Sqrt[3]]}, "MaxTrials" -> 1, "TimeBudget" -> 30]}, r["Statistics"]["Trials"] <= 2], True, TestID -> "R5-per-island-list-trial-budget"]
VerificationTest[Module[{a = Sqrt[5 + 2 Sqrt[6]], b}, b = d[a, True]; SameQ[d[b, True], b]], True, TestID -> "R5-simple-idempotence"]
VerificationTest[Module[{mixed = {1.0, Sqrt[5 + 2 Sqrt[6]]}}, SameQ[d[mixed], mixed]], True, TestID -> "R5-inexact-tree-policy-is-conservative"]
VerificationTest[RadicalDenest2`CertifiedEqualQ[RadicalDenest2`RationalizeDenominator[1/(1 + Sqrt[2])], Sqrt[2] - 1], True, TestID -> "R5-rationalization-certificate"]
VerificationTest[SameQ[RadicalDenest2`Factorc[Sqrt[x^2]], Sqrt[x^2]], True, TestID -> "R5-factor-helper-refuses-symbolic-transform"]
VerificationTest[Module[{a = Sqrt[5 + 2 Sqrt[6]], r}, r = RadicalDenest2`DenestReport[a, "Multipliers" -> {0, Pi, 1.0, 2}]; eq[r["Result"], a]], True, TestID -> "R5-invalid-seeds-do-not-change-value"]
VerificationTest[Module[{a = Sqrt[5 + 2 Sqrt[6]], r}, r = RadicalDenest2`DenestReport[a, "MaxTraceEntries" -> 0]; r["Certificates"] === {} && eq[r["Result"], a]], True, TestID -> "R5-bounded-certificate-records"]
VerificationTest[Module[{a = (2^(1/3) - 1)^(1/3), b}, b = RadicalDenest2`DenestCore[a, "Multipliers" -> {9}, "Factor" -> False]; eq[b, a] && depth[b] == 1], True, TestID -> "R5-ramanujan-cubic-multiplier-nine"]

(* ---------------- R6: review-6, tests/StradImproved.wlt ---------------- *)
VerificationTest[improves[Sqrt[3 + 2 Sqrt[2]], 1 + Sqrt[2], "MaxTrials" -> 0], True, TestID -> "R6-direct-plus"]
VerificationTest[improves[Sqrt[3 - 2 Sqrt[2]], Sqrt[2] - 1, "MaxTrials" -> 0], True, TestID -> "R6-direct-minus"]
VerificationTest[improves[Sqrt[5 + 2 Sqrt[6]], Sqrt[2] + Sqrt[3], "MaxTrials" -> 0], True, TestID -> "R6-two-surds"]
VerificationTest[improves[Sqrt[4 + 3 Sqrt[2]], 2^(1/4) (1 + Sqrt[2]), "MaxTrials" -> 0], True, TestID -> "R6-indirect-plus"]
VerificationTest[improves[Sqrt[-4 + 3 Sqrt[2]], 2^(1/4) (Sqrt[2] - 1), "MaxTrials" -> 0], True, TestID -> "R6-indirect-minus"]
VerificationTest[eq[d[Sqrt[-3 - 2 Sqrt[2]], "MaxTrials" -> 0], I (1 + Sqrt[2])], True, TestID -> "R6-imaginary-square-root"]
VerificationTest[Module[{v = d[Sqrt[3 + 4 I], "MaxTrials" -> 0]}, eq[v, 2 + I] && depth[v] === 0], True, TestID -> "R6-complex-square-root"]
VerificationTest[improves[(26 + 15 Sqrt[3])^(1/3), 2 + Sqrt[3], "MaxTrials" -> 0], True, TestID -> "R6-cubic-quadratic"]
VerificationTest[improves[(2 + Sqrt[5])^(1/3), (1 + Sqrt[5])/2, "MaxTrials" -> 0], True, TestID -> "R6-cubic-golden-ratio"]
VerificationTest[eq[d[(-26 - 15 Sqrt[3])^(1/3), "MaxTrials" -> 0], (-1)^(1/3) (2 + Sqrt[3])], True, TestID -> "R6-principal-negative-cube"]
VerificationTest[improves[(3 + 2 Sqrt[2])^(3/2), (1 + Sqrt[2])^3, "MaxTrials" -> 0], True, TestID -> "R6-rational-power-numerator"]
VerificationTest[eq[d[(3 + 2 Sqrt[2])^(-1/2), "MaxTrials" -> 0], Sqrt[2] - 1], True, TestID -> "R6-reciprocal-root"]
VerificationTest[eq[d[x + Sqrt[3 + 2 Sqrt[2]], "Solver" -> (0 &)] - x, 1 + Sqrt[2]], True, TestID -> "R6-symbolic-host-reject-zero"]
VerificationTest[eq[d[Sqrt[3 + 2 Sqrt[2]], "Solver" -> (-1 - Sqrt[2] &)], 1 + Sqrt[2]], True, TestID -> "R6-reject-opposite-branch"]
VerificationTest[FreeQ[d[Sqrt[3 + 2 Sqrt[2]], "Solver" -> (N[#, 20] &)], _Real], True, TestID -> "R6-reject-inexact-candidate"]
VerificationTest[d[x + Sqrt[2 + Sqrt[2]], "Solver" -> (0 &)] =!= x, True, TestID -> "R6-symbolic-host-without-fastpath"]
VerificationTest[RadicalDenest2`RadicalExpressionQ[Inactive[Cos][Pi/8]], False, TestID -> "R6-grammar-reject-hidden-function"]
VerificationTest[RadicalDenest2`RadicalExpressionQ[Root[#^5 - # - 1 &, 1]], False, TestID -> "R6-grammar-reject-root-object"]
VerificationTest[RadicalDenest2`CertifiedEqualQ[Sqrt[2] + Sqrt[3], Sqrt[3] - Sqrt[2]], False, TestID -> "R6-same-minpoly-not-equality"]
VerificationTest[RadicalDenest2`CertifiedEqualQ[Sqrt[3 + 2 Sqrt[2]], 1 + Sqrt[2]], True, TestID -> "R6-exact-certificate"]
VerificationTest[Block[{$Assumptions = x > 0}, d[Sqrt[x^2]]], Sqrt[x^2], TestID -> "R6-ambient-assumptions-isolated"]
VerificationTest[d[HoldComplete[Sqrt[3 + 2 Sqrt[2]]]], HoldComplete[Sqrt[3 + 2 Sqrt[2]]], TestID -> "R6-held-input-unchanged"]
VerificationTest[d[f[Sqrt[3 + 2 Sqrt[2]]]], f[Sqrt[3 + 2 Sqrt[2]]], TestID -> "R6-unknown-head-not-traversed"]
VerificationTest[d[{1.25, Sqrt[3 + 2 Sqrt[2]]}, "MaxTrials" -> 0], {1.25, Sqrt[3 + 2 Sqrt[2]]}, TestID -> "R6-mixed-exact-inexact-list-is-conservative"]
VerificationTest[d[0], 0, TestID -> "R6-zero"]
VerificationTest[d[7/5], 7/5, TestID -> "R6-rational-no-op"]
VerificationTest[d[Indeterminate], Indeterminate, TestID -> "R6-invalid-value-preserved"]
VerificationTest[d[Sqrt[3 + 2 Sqrt[2]], "TimeBudget" -> 0], Sqrt[3 + 2 Sqrt[2]], TestID -> "R6-zero-budget-no-op"]
VerificationTest[FailureQ[d[Sqrt[2], "MultiplierCap" -> Infinity]], True, TestID -> "R6-infinite-cap-invalid"]
VerificationTest[FailureQ[d[Sqrt[2], "MaxTrials" -> -1]], True, TestID -> "R6-negative-trials-invalid"]
VerificationTest[FailureQ[d[Sqrt[2], "TimeBudget" -> -1]], True, TestID -> "R6-negative-budget-invalid"]
VerificationTest[FailureQ[d[Sqrt[2], "AllLevels" -> "yes"]], True, TestID -> "R6-boolean-option-invalid"]
VerificationTest[FailureQ[d[Sqrt[2], "NotAnOption" -> 1]], True, TestID -> "R6-unknown-option-invalid"]
VerificationTest[Module[{saved = Options[RadicalDenest2`Strad], out}, SetOptions[RadicalDenest2`Strad, "TimeBudget" -> 0]; out = d[Sqrt[3 + 2 Sqrt[2]]]; SetOptions[RadicalDenest2`Strad, Sequence @@ saved]; out], Sqrt[3 + 2 Sqrt[2]], TestID -> "R6-setoptions-respected"]
VerificationTest[d[Sqrt[3 + 2 Sqrt[2]], "TimeBudget" -> 0, "TimeBudget" -> 30], Sqrt[3 + 2 Sqrt[2]], TestID -> "R6-first-explicit-option-wins"]
VerificationTest[RadicalDenest2`DenestReport[Sqrt[1 + Sqrt[2]], "MultiplierCap" -> 0]["Statistics"]["Trials"], 0, TestID -> "R6-zero-cap-no-search"]
VerificationTest[Module[{r = RadicalDenest2`DenestReport[{Sqrt[2 + Sqrt[2]], Sqrt[1 + Sqrt[3]]}, "MaxTrials" -> 1, "MultiplierCap" -> 2, "TimeBudget" -> 10]}, r["Statistics"]["Trials"] <= 2], True, TestID -> "R6-per-island-list-trials"]
VerificationTest[Module[{r = RadicalDenest2`DenestReport[Sqrt[2 + Sqrt[2]], "MultiplierCap" -> 1, "MaxTrials" -> 2, "TimeBudget" -> 10]}, r["Statistics"]["MultipliersAdmitted"] <= 1], True, TestID -> "R6-queue-cap-one-node"]
VerificationTest[Module[{r = RadicalDenest2`DenestReport[Sqrt[3 + 2 Sqrt[2]], "MaxTrials" -> 0]}, Length[r["Certificates"]] > 0 && AllTrue[r["Certificates"], eq[#["After"], #["Before"]] &]], True, TestID -> "R6-recheck-certificate-log"]
VerificationTest[Module[{e = 1/(1 + Sqrt[2])}, eq[e, RadicalDenest2`RationalizeDenominator[e]]], True, TestID -> "R6-rationalization-equality"]
VerificationTest[RadicalDenest2`Factorc[x^2 - 1], x^2 - 1, TestID -> "R6-symbolic-factorc-conservative"]
VerificationTest[Order[{0, 1, 2}, {0, 2, 1}], 1, TestID -> "R6-cost-order-direction"]
VerificationTest[Module[{e = (2^(1/3) - 1)^(1/3), v}, v = RadicalDenest2`DenestCore[e, "Multipliers" -> {9}, "MultiplierCap" -> 1, "MaxTrials" -> 1, "TimeBudget" -> 30]; eq[e, v] && depth[v] < depth[e]], True, TestID -> "R6-ramanujan-forced-multiplier-nine"]

(* ---------------- G: the fifteen misses of KNOWN_GAPS.md ---------------- *)
VerificationTest[improves[(41 - 29 Sqrt[2])^(1/5), (-1)^(1/5) (Sqrt[2] - 1)], True, TestID -> "G-A-C05-negative-fifth-root"]
VerificationTest[improves[(-99 - 70 Sqrt[2])^(1/6), (-1)^(1/6) (1 + Sqrt[2])], True, TestID -> "G-A-C14-negative-sixth-root"]
VerificationTest[improves[Expand[-(1 + 2^(1/3))^5]^(1/5), (-1)^(1/5) (1 + 2^(1/3))], True, TestID -> "G-A-S11"]
VerificationTest[improves[(-239 - 169 Sqrt[2])^(1/7), (-1)^(1/7) (1 + Sqrt[2])], True, TestID -> "G-A-S12"]
VerificationTest[improves[(76 - 44 Sqrt[3])^(1/5), (-1)^(1/5) (Sqrt[3] - 1)], True, TestID -> "G-A-S13"]
VerificationTest[improves[(682 - 305 Sqrt[5])^(1/5), (-1)^(1/5) (Sqrt[5] - 2)], True, TestID -> "G-A-S14"]
VerificationTest[improves[(1393 - 985 Sqrt[2])^(1/9), (-1)^(1/9) (Sqrt[2] - 1)], True, TestID -> "G-A-S15"]
VerificationTest[improves[Expand[(Sqrt[2] - Sqrt[3])^5]^(1/5), (-1)^(1/5) (Sqrt[3] - Sqrt[2])], True, TestID -> "G-A-S20"]
VerificationTest[improves[(7 20^(1/3) - 19)^(1/6), (5/3)^(1/3) - (2/3)^(1/3)], True, TestID -> "G-B-R03-ramanujan-sixth-root"]
VerificationTest[improves[Expand[(2^(1/3) + 3^(1/3))^6]^(1/6), 2^(1/3) + 3^(1/3)], True, TestID -> "G-B-P02"]
VerificationTest[improves[Expand[(2^(1/3) + 5^(1/3))^6]^(1/6), 2^(1/3) + 5^(1/3)], True, TestID -> "G-B-S10"]
VerificationTest[improves[Expand[(2^(1/3) + 3^(1/3))^9]^(1/9), 2^(1/3) + 3^(1/3)], True, TestID -> "G-B-S04"]
VerificationTest[improves[(1296 + 880 Sqrt[2] + 720 Sqrt[3] + 528 Sqrt[6])^(1/6), 1 + Sqrt[2] + Sqrt[3]], True, TestID -> "G-C-S05-factor-extraction"]
VerificationTest[d[Sqrt[1 + Sqrt[3]] + Sqrt[3 + 3 Sqrt[3]] - Sqrt[10 + 6 Sqrt[3]]], 0, TestID -> "G-D-Q21-cancellation"]
VerificationTest[Module[{e = Expand[(Sqrt[2] + Sqrt[3] + Sqrt[5] + Sqrt[7] + Sqrt[11])^2]^(1/2), t, r}, {t, r} = AbsoluteTiming[d[e, "TimeBudget" -> 60]]; eq[r, Sqrt[2] + Sqrt[3] + Sqrt[5] + Sqrt[7] + Sqrt[11]] && t < 60], True, TestID -> "G-E-P13-five-primes-within-budget"]

(* ---------------- A: contracts kept from unified-A ---------------- *)
VerificationTest[improves[(2^(1/3) - 1)^(1/3), (1 - 2^(1/3) + 4^(1/3))/9^(1/3)], True, TestID -> "A-A12-ramanujan-cube-root"]
VerificationTest[improves[Sqrt[28^(1/3) - 3], (98^(1/3) - 28^(1/3) - 1)/3], True, TestID -> "A-K01-ramanujan-square-root"]
VerificationTest[eq[d[(-1 + 2 I Sqrt[2])^(3/2)], -5 + I Sqrt[2]], True, TestID -> "A-C02-complex-three-halves-power"]
VerificationTest[eq[d[Sqrt[-1 + 2 I Sqrt[2]] Sqrt[-2 + 2 I Sqrt[3]]], (1 + I Sqrt[2]) (1 + I Sqrt[3])], True, TestID -> "A-C03-complex-product"]
VerificationTest[eq[d[-Sqrt[3 + 2 Sqrt[2]]], -1 - Sqrt[2]], True, TestID -> "A-C01-negative-target"]
VerificationTest[Module[{r = d[Sqrt[16 - 2 Sqrt[29] + 2 Sqrt[55 - 10 Sqrt[29]]], True]}, eq[r, Sqrt[5] + Sqrt[11 - 2 Sqrt[29]]] && depth[r] === 2], True, TestID -> "A-A30-bfht-partial-denesting"]
VerificationTest[Module[{r = d[Sqrt[16 - 2 Sqrt[29] + 2 Sqrt[55 - 10 Sqrt[29]]]]}, eq[r, Sqrt[5] + Sqrt[11 - 2 Sqrt[29]]] && depth[r] === 2], True, TestID -> "A-A31-bfht-default-levels"]
VerificationTest[eq[d[Root[#^4 - 10 #^2 + 1 &, 4]], Sqrt[2] + Sqrt[3]], True, TestID -> "A-B07-root-input"]
VerificationTest[d[Sqrt[2 + Sqrt[2]]], Sqrt[2 + Sqrt[2]], TestID -> "A-B01-non-denestable-unchanged"]
VerificationTest[d[(1 + Sqrt[2])^(1/3)], (1 + Sqrt[2])^(1/3), TestID -> "A-B03-non-denestable-cube-root-unchanged"]
VerificationTest[d[Sqrt[z^2]], Sqrt[z^2], TestID -> "A-E01-symbolic-untouched"]
VerificationTest[d[Sqrt[x] Sqrt[3 + 2 Sqrt[2]]], Sqrt[x] (1 + Sqrt[2]), TestID -> "A-E06-numeric-factor-inside-symbolic-product"]
VerificationTest[d[Sqrt[3 + 2 Sqrt[2]] + Pi], 1 + Sqrt[2] + Pi, TestID -> "A-K11-transcendental-host"]
VerificationTest[eq[d[Sqrt[2 + Sqrt[3]] + Sqrt[2 - Sqrt[3]]], Sqrt[6]], True, TestID -> "A-A23-sum-recombined"]
VerificationTest[Module[{r = RadicalDenest2`DenestReport[Sqrt[5 + 2 Sqrt[6]] + Sqrt[1 + Sqrt[2]]]}, r["Status"] === "Improved" && eq[r["Result"], Sqrt[2] + Sqrt[3] + Sqrt[1 + Sqrt[2]]]], True, TestID -> "A-report-status-improved"]
VerificationTest[Module[{r = d[1/(Sqrt[2] + Sqrt[3 + 2 Sqrt[2]])]}, eq[r, (2 Sqrt[2] - 1)/7] && depth[r] === 1], True, TestID -> "A-M02-reciprocal-of-a-sum-island"]
VerificationTest[d[(Sqrt[2 - Sqrt[3]] + Sqrt[2 + Sqrt[3]])^2], 6, TestID -> "A-M15-integer-power-of-a-sum-island"]
VerificationTest[Attributes[Print], {Protected}, TestID -> "A-print-untouched"]
End[];
