Get["C:/Users/vresh/AppData/Local/Temp/claude/C--RadicalDenest--claude-worktrees-strad-denesting-analysis-6158e6/8331ac58-d8d2-4638-b75d-79549acb84bf/scratchpad/runner.wl"];
rows = {};
add[r_] := AppendTo[rows, r];
Print["=== H. Helper-level probes ==="];
add@runCase["H01", Factorc[Sqrt[z^2]], None];
add@runCase["H02", Factorc[Sqrt[t + t^2]], None];
add@runCase["H03", Factorc[Sqrt[-x - y]], None];
add@runCase["H04", Factorc[Sqrt[-2 - 2 Sqrt[2]]], Sqrt[-2 - 2 Sqrt[2]]];
add@runCase["H05", Factorc[Sqrt[-(Sqrt[2] + (-1)^(1/3))]], Sqrt[-(Sqrt[2] + (-1)^(1/3))]];
add@runCase["H06", Factorc[Sqrt[(1 + I) (3 + 2 Sqrt[2])]], Sqrt[(1 + I) (3 + 2 Sqrt[2])]];
add@runCase["H07", Factorc[Sqrt[-1 - I]], Sqrt[-1 - I]];
add@runCase["H08", Factorc[Sqrt[-2 - 2 I Sqrt[3]]], Sqrt[-2 - 2 I Sqrt[3]]];
add@runCase["H09", Factorc[Sqrt[(-1 - I Sqrt[3]) (1 + Sqrt[2])]], Sqrt[(-1 - I Sqrt[3]) (1 + Sqrt[2])]];
add@runCase["H10", Factorc[(-3 - 2 Sqrt[2])^(1/3)], (-3 - 2 Sqrt[2])^(1/3)];
add@runCase["H11", Factorc[((-1 + I) (3 + 2 Sqrt[2]))^(1/3)], ((-1 + I) (3 + 2 Sqrt[2]))^(1/3)];
add@runCase["H12", Factorc[Sqrt[2] + Sqrt[3]], Sqrt[2] + Sqrt[3]];
add@runCase["H13", Factorc[(1 + Sqrt[2])^2], (1 + Sqrt[2])^2];
add@runCase["H14", Factorc[Sqrt[8 + 4 Sqrt[3]]], Sqrt[8 + 4 Sqrt[3]]];
add@runCase["H15", Factorc[Sqrt[-8 - 4 Sqrt[3]]], Sqrt[-8 - 4 Sqrt[3]]];
add@runCase["H16", Factorc[Sqrt[(-1)^(1/3) (3 + 2 Sqrt[2])]], Sqrt[(-1)^(1/3) (3 + 2 Sqrt[2])]];
add@runCase["H17", Factorc[Sqrt[(-1)^(2/3) (3 + 2 Sqrt[2])]], Sqrt[(-1)^(2/3) (3 + 2 Sqrt[2])]];
add@runCase["H18", Factorc[Sqrt[x^4]], None];
add@runCase["H19", Factorc[(x^2)^(1/3)], None];
add@runCase["H20", Factorc[Sqrt[4 x^2 + 4 x^3]], None];
add@runCase["H21", Factorc[Sqrt[-3 - 2 Sqrt[2]]], Sqrt[-3 - 2 Sqrt[2]]];
add@runCase["H22", Factorc[Sqrt[(-1 + I Sqrt[3]) (-1 + I Sqrt[3])]], Sqrt[(-1 + I Sqrt[3]) (-1 + I Sqrt[3])]];
add@runCase["H23", Factorc[Sqrt[-(1 + Sqrt[2]) - (1 + Sqrt[2]) I Sqrt[3]]], Sqrt[-(1 + Sqrt[2]) - (1 + Sqrt[2]) I Sqrt[3]]];
Print["--- RationalizeDenominator ---"];
add@runCase["R01", RationalizeDenominator[1/(1 + Sqrt[2])], Sqrt[2] - 1];
add@runCase["R02", RationalizeDenominator[1/(Sqrt[2] + Sqrt[3])], Sqrt[3] - Sqrt[2]];
add@runCase["R03", RationalizeDenominator[1/(1 + I Sqrt[2])], (1 - I Sqrt[2])/3];
add@runCase["R04", RationalizeDenominator[(1 + Sqrt[2])/(Sqrt[2] - Sqrt[3])], (1 + Sqrt[2])/(Sqrt[2] - Sqrt[3])];
add@runCase["R05", RationalizeDenominator[x/(1 + Sqrt[2])], None];
add@runCase["R06", RationalizeDenominator[1/2 + 1/Sqrt[2]], 1/2 + 1/Sqrt[2]];
add@runCase["R07", RationalizeDenominator[1/Sqrt[2]], 1/Sqrt[2]];
add@runCase["R08", RationalizeDenominator[1/(1 + 2^(1/3))], 1/(1 + 2^(1/3))];
add@runCase["R09", RationalizeDenominator[1/Sqrt[1 + Sqrt[2]]], 1/Sqrt[1 + Sqrt[2]]];
add@runCase["R10", RationalizeDenominator[0], 0];
add@runCase["R11", RationalizeDenominator[1/x], None];
Print["--- Marker/context collisions ---"];
add@runCase["M01", DenestRadicals3[f[1], False, Identity], None];
add@runCase["M02", DenestRadicals3[g[1], False, Identity], None];
add@runCase["M03", DenestRadicals3[f[Sqrt[3 + 2 Sqrt[2]]], False, Identity], None];
Print["--- nesting helpers ---"];
add@runCase["N01", maxnestdepth[Sqrt[3 + 2 Sqrt[2]], MatchQ[#, Power[_, _Rational]] &], None];
add@runCase["N02", maxnestdepth[(1 + 2^(1/3))^3, MatchQ[#, Power[_, _Rational]] &], None];
add@runCase["N03", LCM @@ (maxnestdepth[(1 + 2^(1/3))^3, MatchQ[#, Power[_, _Rational]] &] /. {Power[base_, exp_], _} :> Denominator[exp]), None];
add@runCase["N04", maxnestdepth[Sqrt[1 + 2^(1/3)] (1 + Sqrt[2])^(1/3), MatchQ[#, Power[_, _Rational]] &], None];
add@runCase["N05", nestdepthsort[Sqrt[3 + 2 Sqrt[3 + 2 Sqrt[2]]], MatchQ[#, Power[_, _Rational]] &], None];
add@runCase["N06", maxnestdepth[Sqrt[3 + 2 Sqrt[2]] + (5 + 2 Sqrt[6])^(1/3), MatchQ[#, Power[_, _Rational]] &], None];
Print["--- comparator and slice ---"];
add@runCase["S01", Sort[{{2, 1}, {3, 1}, {5, 1}, {7, 1}, {11, 1}, {13, 1}, {2003, 1}}, #1[[1]] <= #[[2]] &], None];
add@runCase["S02", Module[{p = {2, 3, 5, 7, 11, 0}}, DeleteCases[p, 0][[1 ;; Min[10, Length[p]]]]], None];
add@runCase["S03", ComplexitySort[{6, Sqrt[2], 2, 3, 1 + Sqrt[2], 10, -3}], None];
add@runCase["S04", PossibleZeroQ[Sqrt[2] - FromContinuedFraction[ContinuedFraction[Sqrt[2], 400]]], None];
add@runCase["S05", PossibleZeroQ[Sqrt[2] - FromContinuedFraction[ContinuedFraction[Sqrt[2], 400]], Method -> "ExactAlgebraics"], None];
add@runCase["S06", PossibleZeroQ[Sqrt[2] - Root[#^2 - 2 + 10^-100 &, 2]], None];
add@runCase["S07", DeleteDuplicates[{1 + Sqrt[2], Sqrt[3 + 2 Sqrt[2]], (1 + Sqrt[2])}], None];
Put[rows, "C:/Users/vresh/AppData/Local/Temp/claude/C--RadicalDenest--claude-worktrees-strad-denesting-analysis-6158e6/8331ac58-d8d2-4638-b75d-79549acb84bf/scratchpad/exp_helpers_rows.m"];
Print["DONE"];
