(* Regression suite for src/corrected/StradFixed3.wl (context RadicalDenest3`).

   Groups:  R4-*, R5-*, R6-* translate the suites of review-4/5/6 (kept from unified-B),
            G-*  are the fifteen inputs of src/corrected/KNOWN_GAPS.md,
            A-*  are contracts kept from the unified-A battery,
            C-*  translate the suites of review-7 (C-R7), review-8 (C-R8) and
                 review-9 (C-R9) onto the names, arities and contracts of
                 StradFixed3, plus the unified-C controls (C-U).
   Options and report keys of the reviews' proposals were mapped onto those of
   StradFixed3 (see unified-C, Section "Translating the reviews' test suites").
   Run with tests/run_tests.wls in a fresh kernel. *)

Begin["RadicalDenest3Tests`"];
ClearAll[d, eq, depth, improves, x, y, f, h];
d[e_, opts___] := RadicalDenest3`Strad[e, opts];
eq[a_, b_] := TrueQ[RootReduce[a - b] === 0];
depth[e_] := RadicalDenest3`RadicalDepth[e];
improves[e_, target_, opts___] := Module[{v = d[e, opts]}, eq[v, target] && depth[v] < depth[e]];

(* ---------------- R4: review-4, tests/Regression.wlt ---------------- *)
VerificationTest[RadicalDenest3`CertifiedEqualQ[Sqrt[5 + 2 Sqrt[6]], Sqrt[2] + Sqrt[3]], True, TestID -> "R4-exact-equality-positive"]
VerificationTest[RadicalDenest3`CertifiedEqualQ[Sqrt[3 - 2 Sqrt[2]], 1 - Sqrt[2]], False, TestID -> "R4-reject-wrong-square-root-branch"]
VerificationTest[RadicalDenest3`CertifiedEqualQ[Sqrt[2], Sqrt[2] + 10^-100], False, TestID -> "R4-no-numerical-tolerance-acceptance"]
VerificationTest[RadicalDenest3`CertifiedEqualQ[x, x], False, TestID -> "R4-symbolic-equality-is-not-algebraic-certificate"]
VerificationTest[{RadicalDenest3`ExactAlgebraicQ[Pi], RadicalDenest3`ExactAlgebraicQ[N[Sqrt[2]]], RadicalDenest3`ExactAlgebraicQ[(1 + I)/2]}, {False, False, True}, TestID -> "R4-supported-exact-domain"]
VerificationTest[Block[{RadicalDenest3`Private`$cfg = Association[Options[RadicalDenest3`Strad]]}, RadicalDenest3`Private`validPolynomialQ[$Failed, x]], False, TestID -> "R4-failed-is-not-an-accepted-polynomial"]
VerificationTest[Block[{RadicalDenest3`Private`$cfg = Association[Options[RadicalDenest3`Strad]]}, RadicalDenest3`Private`validPolynomialQ[7, x]], False, TestID -> "R4-constant-is-not-a-minimal-polynomial"]
VerificationTest[RadicalDenest3`RadicalDepth[Root[#^5 - # - 1 &, 1]], 0, TestID -> "R4-root-payload-is-opaque"]
VerificationTest[First[RadicalDenest3`RadicalCost[Root[#^5 - # - 1 &, 1]]], 1, TestID -> "R4-root-representation-is-not-free"]
VerificationTest[RadicalDenest3`RadicalCost[{}], {0, 0, 0, LeafCount[{}], 0}, TestID -> "R4-empty-list-metrics"]
VerificationTest[improves[Sqrt[5 + 2 Sqrt[6]], Sqrt[2] + Sqrt[3]], True, TestID -> "R4-direct-quadratic-denesting"]
VerificationTest[improves[Sqrt[3 - 2 Sqrt[2]], Sqrt[2] - 1], True, TestID -> "R4-negative-coefficient-positive-root"]
VerificationTest[improves[Sqrt[4 + 3 Sqrt[2]], 2^(1/4) (1 + Sqrt[2])], True, TestID -> "R4-indirect-fourth-root-minus-sign"]
VerificationTest[improves[Sqrt[-4 + 3 Sqrt[2]], 2^(1/4) (Sqrt[2] - 1)], True, TestID -> "R4-indirect-negative-rational-part"]
VerificationTest[eq[d[Sqrt[-3 - 2 Sqrt[2]]], I (1 + Sqrt[2])], True, TestID -> "R4-negative-radicand-principal-square-root"]
VerificationTest[improves[(49 + 20 Sqrt[6])^(1/4), Sqrt[2] + Sqrt[3], True], True, TestID -> "R4-composite-index-without-cost-neutral-stall"]
VerificationTest[eq[d[(3 + 2 Sqrt[2])^(-1/2)], Sqrt[2] - 1], True, TestID -> "R4-negative-rational-exponent"]
VerificationTest[improves[(7 + 5 Sqrt[2])^(1/3), 1 + Sqrt[2]], True, TestID -> "R4-cubic-trace-norm"]
VerificationTest[Module[{e = (7 - 5 Sqrt[2])^(1/3), r}, r = d[e]; eq[r, e] && ! eq[r, 1 - Sqrt[2]]], True, TestID -> "R4-negative-real-cubic-is-not-real-root"]
VerificationTest[improves[Sqrt[5^(1/3) - 4^(1/3)], (2^(1/3) + 20^(1/3) - 25^(1/3))/3], True, TestID -> "R4-honsbeek-ramanujan-square-of-cube-roots"]
VerificationTest[Module[{e = x + Sqrt[5 + 2 Sqrt[6]], r}, r = d[e, "Solver" -> (0 &), "Factor" -> False]; eq[(r - x) - (e - x), 0]], True, TestID -> "R4-untrusted-solver-in-symbolic-host"]
VerificationTest[Module[{e = Sqrt[x^2] + Sqrt[5 + 2 Sqrt[6]], r}, r = Block[{$Assumptions = x > 0}, d[e]]; eq[(r - e) /. x -> -2, 0]], True, TestID -> "R4-ambient-assumptions-do-not-rewrite-host"]
VerificationTest[Module[{e = f[Sqrt[5 + 2 Sqrt[6]]]}, SameQ[d[e], e]], True, TestID -> "R4-unknown-head-is-opaque"]
VerificationTest[SameQ[d[HoldComplete[Sqrt[5 + 2 Sqrt[6]]]], HoldComplete[Sqrt[5 + 2 Sqrt[6]]]], True, TestID -> "R4-held-input-is-opaque"]
VerificationTest[Module[{e = (x + 1) (x - 1)}, SameQ[RadicalDenest3`Factorc[e], e]], True, TestID -> "R4-symbolic-factorc-is-conservative"]
VerificationTest[RadicalDenest3`CertifiedEqualQ[RadicalDenest3`RationalizeDenominator[1/(1 + Sqrt[2])], Sqrt[2] - 1], True, TestID -> "R4-horner-inverse"]
VerificationTest[RadicalDenest3`CertifiedEqualQ[RadicalDenest3`RationalizeDenominator[x/(1 + Sqrt[2])] /. x -> 1, Sqrt[2] - 1], True, TestID -> "R4-symbolic-numerator-local-inverse-certificate"]
VerificationTest[RadicalDenest3`CertifiedEqualQ[Sqrt[I] (-1 + I), -Sqrt[2]], True, TestID -> "R4-aggregate-positive-factor-is-not-termwise-license"]
VerificationTest[Module[{saved = Options[RadicalDenest3`Strad], e = Sqrt[5 + 2 Sqrt[6]], r}, SetOptions[RadicalDenest3`Strad, "TimeBudget" -> 0]; r = d[e]; SetOptions[RadicalDenest3`Strad, Sequence @@ saved]; SameQ[r, e]], True, TestID -> "R4-setoptions-strad-is-effective"]
VerificationTest[Module[{saved = Options[RadicalDenest3`DenestRadicals], e = Sqrt[5 + 2 Sqrt[6]], r}, SetOptions[RadicalDenest3`DenestRadicals, "TimeBudget" -> 0]; r = RadicalDenest3`DenestRadicals[e]; SetOptions[RadicalDenest3`DenestRadicals, Sequence @@ saved]; SameQ[r, e]], True, TestID -> "R4-setoptions-wrapper-is-effective"]
VerificationTest[Module[{r = RadicalDenest3`DenestReport[Sqrt[5 + 2 Sqrt[6]], "TimeBudget" -> 0]}, r["Statistics"]["Trials"] === 0 && MemberQ[r["Limits"], "TimeBudget"] && SameQ[r["Result"], Sqrt[5 + 2 Sqrt[6]]]], True, TestID -> "R4-zero-budget-no-work"]
VerificationTest[And @@ (FailureQ[d[Sqrt[1 + Sqrt[2]], #]] & /@ {"MultiplierCap" -> Infinity, "MultiplierCap" -> -1, "MultiplierCap" -> 1/2, "MaxTrials" -> -1, "TimeBudget" -> Infinity, "TimeBudget" -> -1, "MaxRootIndex" -> 0, "AllLevels" -> "yes", "Bogus" -> 1}), True, TestID -> "R4-invalid-options-fail-explicitly"]
VerificationTest[Module[{r = RadicalDenest3`DenestReport[Sqrt[1 + Sqrt[2]], "Multipliers" -> Range[20], "MultiplierCap" -> 1, "TimeBudget" -> 20]}, r["Statistics"]["MultipliersAdmitted"] <= 1 && r["Statistics"]["Trials"] <= 1], True, TestID -> "R4-forced-list-obeys-cap"]
VerificationTest[Module[{r = RadicalDenest3`DenestReport[{Sqrt[1 + Sqrt[2]], Sqrt[1 + Sqrt[3]]}, "MaxTrials" -> 1, "Multipliers" -> {1}, "TimeBudget" -> 30]}, r["Statistics"]["Trials"] <= 2], True, TestID -> "R4-trial-budget-per-island-across-list"]
VerificationTest[Module[{r = RadicalDenest3`DenestReport[Sqrt[1 + Sqrt[2]], "Trace" -> True, "MaxTraceEntries" -> 1, "MaxTrials" -> 2, "TimeBudget" -> 20]}, Length[r["Trace"]] <= 1], True, TestID -> "R4-bounded-diagnostics"]
VerificationTest[Module[{e = Sqrt[5 + 2 Sqrt[6]], r}, r = d[e, "Solver" -> (Throw["bad", "callback"] &)]; eq[r, e]], True, TestID -> "R4-callback-throw-is-not-a-rewrite"]
VerificationTest[Module[{examples = {Sqrt[2 + Sqrt[3]], Sqrt[4 + 3 Sqrt[2]], (7 - 5 Sqrt[2])^(1/3), (49 + 20 Sqrt[6])^(1/4)}, results}, results = d[examples, True]; And @@ MapThread[(eq[#1, #2] && Order[RadicalDenest3`RadicalCost[#1], RadicalDenest3`RadicalCost[#2]] =!= -1) &, {results, examples}]], True, TestID -> "R4-each-example-equal-and-no-more-expensive"]

(* ---------------- R5: review-5, tests/regression.wlt ---------------- *)
VerificationTest[eq[d[Sqrt[5 + 2 Sqrt[6]]], Sqrt[2] + Sqrt[3]], True, TestID -> "R5-direct-square-value"]
VerificationTest[depth[d[Sqrt[5 + 2 Sqrt[6]]]], 1, TestID -> "R5-direct-square-depth"]
VerificationTest[eq[d[Sqrt[4 + 3 Sqrt[2]]], 2^(1/4) (1 + Sqrt[2])], True, TestID -> "R5-indirect-fourth-root-value"]
VerificationTest[depth[d[Sqrt[4 + 3 Sqrt[2]]]], 1, TestID -> "R5-indirect-fourth-root-depth"]
VerificationTest[eq[d[Sqrt[3 - 2 Sqrt[2]]], Sqrt[2] - 1], True, TestID -> "R5-small-positive-branch"]
VerificationTest[eq[d[Sqrt[-5 - 2 Sqrt[6]]], I (Sqrt[2] + Sqrt[3])], True, TestID -> "R5-negative-radicand-principal-square-root"]
VerificationTest[eq[d[(41 - 29 Sqrt[2])^(1/5)], (41 - 29 Sqrt[2])^(1/5)], True, TestID -> "R5-principal-fifth-power-preserved"]
VerificationTest[RadicalDenest3`CertifiedEqualQ[1 - Sqrt[2], (41 - 29 Sqrt[2])^(1/5)], False, TestID -> "R5-real-fifth-root-is-not-principal-power"]
VerificationTest[Module[{a = Sqrt[5 + 2 Sqrt[6]], r}, r = d[x + a, "Solver" -> Function[z, 0]]; eq[r - x, a]], True, TestID -> "R5-bad-zero-solver-in-symbolic-host-rejected"]
VerificationTest[Module[{a = Sqrt[5 + 2 Sqrt[6]], r}, r = d[x + a, "Solver" -> Function[z, $Failed]]; FreeQ[r, $Failed] && eq[r - x, a]], True, TestID -> "R5-failed-solver-does-not-leak"]
VerificationTest[Module[{a = Sqrt[5 + 2 Sqrt[6]], r}, r = d[x + a, "Solver" -> Function[z, 1.41421356237]]; FreeQ[r, _Real] && eq[r - x, a]], True, TestID -> "R5-approximate-solver-does-not-leak"]
VerificationTest[Block[{$Assumptions = x > 0}, SameQ[d[Sqrt[x^2]], Sqrt[x^2]]], True, TestID -> "R5-ambient-assumptions-do-not-rewrite-host"]
VerificationTest[SameQ[d[h[Sqrt[5 + 2 Sqrt[6]]]], h[Sqrt[5 + 2 Sqrt[6]]]], True, TestID -> "R5-unknown-head-is-opaque"]
VerificationTest[RadicalDenest3`ExactAlgebraicQ[Pi], False, TestID -> "R5-transcendental-constant-rejected"]
VerificationTest[RadicalDenest3`ExactAlgebraicQ[Sqrt[2] + 3^(1/3)], True, TestID -> "R5-explicit-algebraic-grammar"]
VerificationTest[RadicalDenest3`EqualityStatus[Sqrt[2], -Sqrt[2]], "Different", TestID -> "R5-conjugates-distinguished"]
VerificationTest[RadicalDenest3`EqualityStatus[Sqrt[2], x], "Unknown", TestID -> "R5-non-algebraic-comparison-is-unknown"]
VerificationTest[Module[{a = Sqrt[5 + 2 Sqrt[6]], r}, r = RadicalDenest3`DenestReport[a, {"TimeBudget" -> 0}]; {r["Result"] === a, r["Statistics"]["Trials"], r["Status"]}], {True, 0, "Disabled"}, TestID -> "R5-zero-total-budget-is-noop"]
VerificationTest[FailureQ[RadicalDenest3`DenestReport[Sqrt[5 + 2 Sqrt[6]], "MaxTrials" -> -1]], True, TestID -> "R5-invalid-integer-option"]
VerificationTest[FailureQ[RadicalDenest3`DenestReport[Sqrt[5 + 2 Sqrt[6]], "TimeBudget" -> "bad"]], True, TestID -> "R5-invalid-time-option"]
VerificationTest[FailureQ[RadicalDenest3`DenestReport[Sqrt[5 + 2 Sqrt[6]], "UnknownOption" -> 1]], True, TestID -> "R5-unknown-option-rejected"]
VerificationTest[Module[{defaults = Options[RadicalDenest3`Strad], a = Sqrt[5 + 2 Sqrt[6]], result}, SetOptions[RadicalDenest3`Strad, "TimeBudget" -> 0]; result = d[a]; SetOptions[RadicalDenest3`Strad, Sequence @@ defaults]; SameQ[result, a]], True, TestID -> "R5-SetOptions-on-alias-is-honored"]
VerificationTest[Module[{a = Sqrt[5 + 2 Sqrt[6]], r}, r = RadicalDenest3`DenestReport[a, "MaxTrials" -> 0]; r["Statistics"]["Trials"] === 0 && eq[r["Result"], a] && depth[r["Result"]] === 1], True, TestID -> "R5-zero-trials-disables-only-multiplier-search"]
VerificationTest[Module[{r = RadicalDenest3`DenestReport[{Sqrt[2 + Sqrt[2]], Sqrt[3 + Sqrt[3]]}, "MaxTrials" -> 1, "TimeBudget" -> 30]}, r["Statistics"]["Trials"] <= 2], True, TestID -> "R5-per-island-list-trial-budget"]
VerificationTest[Module[{a = Sqrt[5 + 2 Sqrt[6]], b}, b = d[a, True]; SameQ[d[b, True], b]], True, TestID -> "R5-simple-idempotence"]
VerificationTest[Module[{mixed = {1.0, Sqrt[5 + 2 Sqrt[6]]}}, SameQ[d[mixed], mixed]], True, TestID -> "R5-inexact-tree-policy-is-conservative"]
VerificationTest[RadicalDenest3`CertifiedEqualQ[RadicalDenest3`RationalizeDenominator[1/(1 + Sqrt[2])], Sqrt[2] - 1], True, TestID -> "R5-rationalization-certificate"]
VerificationTest[SameQ[RadicalDenest3`Factorc[Sqrt[x^2]], Sqrt[x^2]], True, TestID -> "R5-factor-helper-refuses-symbolic-transform"]
VerificationTest[Module[{a = Sqrt[5 + 2 Sqrt[6]], r}, r = RadicalDenest3`DenestReport[a, "Multipliers" -> {0, Pi, 1.0, 2}]; eq[r["Result"], a]], True, TestID -> "R5-invalid-seeds-do-not-change-value"]
VerificationTest[Module[{a = Sqrt[5 + 2 Sqrt[6]], r}, r = RadicalDenest3`DenestReport[a, "MaxTraceEntries" -> 0]; r["Certificates"] === {} && eq[r["Result"], a]], True, TestID -> "R5-bounded-certificate-records"]
VerificationTest[Module[{a = (2^(1/3) - 1)^(1/3), b}, b = RadicalDenest3`DenestCore[a, "Multipliers" -> {9}, "Factor" -> False]; eq[b, a] && depth[b] == 1], True, TestID -> "R5-ramanujan-cubic-multiplier-nine"]

(* ---------------- R6: review-6, tests/StradImproved.wlt ---------------- *)
VerificationTest[improves[Sqrt[3 + 2 Sqrt[2]], 1 + Sqrt[2], "MaxTrials" -> 0], True, TestID -> "R6-direct-plus"]
VerificationTest[improves[Sqrt[3 - 2 Sqrt[2]], Sqrt[2] - 1, "MaxTrials" -> 0], True, TestID -> "R6-direct-minus"]
VerificationTest[improves[Sqrt[5 + 2 Sqrt[6]], Sqrt[2] + Sqrt[3], "MaxTrials" -> 0], True, TestID -> "R6-two-surds"]
VerificationTest[improves[Sqrt[4 + 3 Sqrt[2]], 2^(1/4) (1 + Sqrt[2]), "MaxTrials" -> 0], True, TestID -> "R6-indirect-plus"]
VerificationTest[improves[Sqrt[-4 + 3 Sqrt[2]], 2^(1/4) (Sqrt[2] - 1), "MaxTrials" -> 0], True, TestID -> "R6-indirect-minus"]
VerificationTest[eq[d[Sqrt[-3 - 2 Sqrt[2]], "MaxTrials" -> 0], I (1 + Sqrt[2])], True, TestID -> "R6-imaginary-square-root"]
VerificationTest[Module[{v = d[Sqrt[3 + 4 I], "MaxTrials" -> 0]}, eq[v, 2 + I] && depth[v] === 0], True, TestID -> "R6-complex-square-root"]
VerificationTest[improves[(26 + 15 Sqrt[3])^(1/3), 2 + Sqrt[3], "MaxTrials" -> 0], True, TestID -> "R6-cubic-quadratic"]
VerificationTest[improves[(2 + Sqrt[5])^(1/3), (1 + Sqrt[5])/2, "MaxTrials" -> 0], True, TestID -> "R6-cubic-golden-ratio"]
VerificationTest[eq[d[(-26 - 15 Sqrt[3])^(1/3), "MaxTrials" -> 0], (-1)^(1/3) (2 + Sqrt[3])], True, TestID -> "R6-principal-negative-cube"]
VerificationTest[improves[(3 + 2 Sqrt[2])^(3/2), (1 + Sqrt[2])^3, "MaxTrials" -> 0], True, TestID -> "R6-rational-power-numerator"]
VerificationTest[eq[d[(3 + 2 Sqrt[2])^(-1/2), "MaxTrials" -> 0], Sqrt[2] - 1], True, TestID -> "R6-reciprocal-root"]
VerificationTest[eq[d[x + Sqrt[3 + 2 Sqrt[2]], "Solver" -> (0 &)] - x, 1 + Sqrt[2]], True, TestID -> "R6-symbolic-host-reject-zero"]
VerificationTest[eq[d[Sqrt[3 + 2 Sqrt[2]], "Solver" -> (-1 - Sqrt[2] &)], 1 + Sqrt[2]], True, TestID -> "R6-reject-opposite-branch"]
VerificationTest[FreeQ[d[Sqrt[3 + 2 Sqrt[2]], "Solver" -> (N[#, 20] &)], _Real], True, TestID -> "R6-reject-inexact-candidate"]
VerificationTest[d[x + Sqrt[2 + Sqrt[2]], "Solver" -> (0 &)] =!= x, True, TestID -> "R6-symbolic-host-without-fastpath"]
VerificationTest[RadicalDenest3`RadicalExpressionQ[Inactive[Cos][Pi/8]], False, TestID -> "R6-grammar-reject-hidden-function"]
VerificationTest[RadicalDenest3`RadicalExpressionQ[Root[#^5 - # - 1 &, 1]], False, TestID -> "R6-grammar-reject-root-object"]
VerificationTest[RadicalDenest3`CertifiedEqualQ[Sqrt[2] + Sqrt[3], Sqrt[3] - Sqrt[2]], False, TestID -> "R6-same-minpoly-not-equality"]
VerificationTest[RadicalDenest3`CertifiedEqualQ[Sqrt[3 + 2 Sqrt[2]], 1 + Sqrt[2]], True, TestID -> "R6-exact-certificate"]
VerificationTest[Block[{$Assumptions = x > 0}, d[Sqrt[x^2]]], Sqrt[x^2], TestID -> "R6-ambient-assumptions-isolated"]
VerificationTest[d[HoldComplete[Sqrt[3 + 2 Sqrt[2]]]], HoldComplete[Sqrt[3 + 2 Sqrt[2]]], TestID -> "R6-held-input-unchanged"]
VerificationTest[d[f[Sqrt[3 + 2 Sqrt[2]]]], f[Sqrt[3 + 2 Sqrt[2]]], TestID -> "R6-unknown-head-not-traversed"]
VerificationTest[d[{1.25, Sqrt[3 + 2 Sqrt[2]]}, "MaxTrials" -> 0], {1.25, Sqrt[3 + 2 Sqrt[2]]}, TestID -> "R6-mixed-exact-inexact-list-is-conservative"]
VerificationTest[d[0], 0, TestID -> "R6-zero"]
VerificationTest[d[7/5], 7/5, TestID -> "R6-rational-no-op"]
VerificationTest[d[Indeterminate], Indeterminate, TestID -> "R6-invalid-value-preserved"]
VerificationTest[d[Sqrt[3 + 2 Sqrt[2]], "TimeBudget" -> 0], Sqrt[3 + 2 Sqrt[2]], TestID -> "R6-zero-budget-no-op"]
VerificationTest[FailureQ[d[Sqrt[2], "MultiplierCap" -> Infinity]], True, TestID -> "R6-infinite-cap-invalid"]
VerificationTest[FailureQ[d[Sqrt[2], "MaxTrials" -> -1]], True, TestID -> "R6-negative-trials-invalid"]
VerificationTest[FailureQ[d[Sqrt[2], "TimeBudget" -> -1]], True, TestID -> "R6-negative-budget-invalid"]
VerificationTest[FailureQ[d[Sqrt[2], "AllLevels" -> "yes"]], True, TestID -> "R6-boolean-option-invalid"]
VerificationTest[FailureQ[d[Sqrt[2], "NotAnOption" -> 1]], True, TestID -> "R6-unknown-option-invalid"]
VerificationTest[Module[{saved = Options[RadicalDenest3`Strad], out}, SetOptions[RadicalDenest3`Strad, "TimeBudget" -> 0]; out = d[Sqrt[3 + 2 Sqrt[2]]]; SetOptions[RadicalDenest3`Strad, Sequence @@ saved]; out], Sqrt[3 + 2 Sqrt[2]], TestID -> "R6-setoptions-respected"]
VerificationTest[d[Sqrt[3 + 2 Sqrt[2]], "TimeBudget" -> 0, "TimeBudget" -> 30], Sqrt[3 + 2 Sqrt[2]], TestID -> "R6-first-explicit-option-wins"]
VerificationTest[RadicalDenest3`DenestReport[Sqrt[1 + Sqrt[2]], "MultiplierCap" -> 0]["Statistics"]["Trials"], 0, TestID -> "R6-zero-cap-no-search"]
VerificationTest[Module[{r = RadicalDenest3`DenestReport[{Sqrt[2 + Sqrt[2]], Sqrt[1 + Sqrt[3]]}, "MaxTrials" -> 1, "MultiplierCap" -> 2, "TimeBudget" -> 10]}, r["Statistics"]["Trials"] <= 2], True, TestID -> "R6-per-island-list-trials"]
VerificationTest[Module[{r = RadicalDenest3`DenestReport[Sqrt[2 + Sqrt[2]], "MultiplierCap" -> 1, "MaxTrials" -> 2, "TimeBudget" -> 10]}, r["Statistics"]["MultipliersAdmitted"] <= 1], True, TestID -> "R6-queue-cap-one-node"]
VerificationTest[Module[{r = RadicalDenest3`DenestReport[Sqrt[3 + 2 Sqrt[2]], "MaxTrials" -> 0]}, Length[r["Certificates"]] > 0 && AllTrue[r["Certificates"], eq[#["After"], #["Before"]] &]], True, TestID -> "R6-recheck-certificate-log"]
VerificationTest[Module[{e = 1/(1 + Sqrt[2])}, eq[e, RadicalDenest3`RationalizeDenominator[e]]], True, TestID -> "R6-rationalization-equality"]
VerificationTest[RadicalDenest3`Factorc[x^2 - 1], x^2 - 1, TestID -> "R6-symbolic-factorc-conservative"]
VerificationTest[Order[{0, 1, 2}, {0, 2, 1}], 1, TestID -> "R6-cost-order-direction"]
VerificationTest[Module[{e = (2^(1/3) - 1)^(1/3), v}, v = RadicalDenest3`DenestCore[e, "Multipliers" -> {9}, "MultiplierCap" -> 1, "MaxTrials" -> 1, "TimeBudget" -> 30]; eq[e, v] && depth[v] < depth[e]], True, TestID -> "R6-ramanujan-forced-multiplier-nine"]

(* ---------------- G: the fifteen misses of KNOWN_GAPS.md ---------------- *)
VerificationTest[improves[(41 - 29 Sqrt[2])^(1/5), (-1)^(1/5) (Sqrt[2] - 1)], True, TestID -> "G-A-C05-negative-fifth-root"]
VerificationTest[improves[(-99 - 70 Sqrt[2])^(1/6), (-1)^(1/6) (1 + Sqrt[2])], True, TestID -> "G-A-C14-negative-sixth-root"]
VerificationTest[improves[Expand[-(1 + 2^(1/3))^5]^(1/5), (-1)^(1/5) (1 + 2^(1/3))], True, TestID -> "G-A-S11"]
VerificationTest[improves[(-239 - 169 Sqrt[2])^(1/7), (-1)^(1/7) (1 + Sqrt[2])], True, TestID -> "G-A-S12"]
VerificationTest[improves[(76 - 44 Sqrt[3])^(1/5), (-1)^(1/5) (Sqrt[3] - 1)], True, TestID -> "G-A-S13"]
VerificationTest[improves[(682 - 305 Sqrt[5])^(1/5), (-1)^(1/5) (Sqrt[5] - 2)], True, TestID -> "G-A-S14"]
VerificationTest[improves[(1393 - 985 Sqrt[2])^(1/9), (-1)^(1/9) (Sqrt[2] - 1)], True, TestID -> "G-A-S15"]
VerificationTest[improves[Expand[(Sqrt[2] - Sqrt[3])^5]^(1/5), (-1)^(1/5) (Sqrt[3] - Sqrt[2])], True, TestID -> "G-A-S20"]
VerificationTest[improves[(7 20^(1/3) - 19)^(1/6), (5/3)^(1/3) - (2/3)^(1/3)], True, TestID -> "G-B-R03-ramanujan-sixth-root"]
VerificationTest[improves[Expand[(2^(1/3) + 3^(1/3))^6]^(1/6), 2^(1/3) + 3^(1/3)], True, TestID -> "G-B-P02"]
VerificationTest[improves[Expand[(2^(1/3) + 5^(1/3))^6]^(1/6), 2^(1/3) + 5^(1/3)], True, TestID -> "G-B-S10"]
VerificationTest[improves[Expand[(2^(1/3) + 3^(1/3))^9]^(1/9), 2^(1/3) + 3^(1/3)], True, TestID -> "G-B-S04"]
VerificationTest[improves[(1296 + 880 Sqrt[2] + 720 Sqrt[3] + 528 Sqrt[6])^(1/6), 1 + Sqrt[2] + Sqrt[3]], True, TestID -> "G-C-S05-factor-extraction"]
VerificationTest[d[Sqrt[1 + Sqrt[3]] + Sqrt[3 + 3 Sqrt[3]] - Sqrt[10 + 6 Sqrt[3]]], 0, TestID -> "G-D-Q21-cancellation"]
VerificationTest[Module[{e = Expand[(Sqrt[2] + Sqrt[3] + Sqrt[5] + Sqrt[7] + Sqrt[11])^2]^(1/2), t, r}, {t, r} = AbsoluteTiming[d[e, "TimeBudget" -> 60]]; eq[r, Sqrt[2] + Sqrt[3] + Sqrt[5] + Sqrt[7] + Sqrt[11]] && t < 60], True, TestID -> "G-E-P13-five-primes-within-budget"]

(* ---------------- A: contracts kept from unified-A ---------------- *)
VerificationTest[improves[(2^(1/3) - 1)^(1/3), (1 - 2^(1/3) + 4^(1/3))/9^(1/3)], True, TestID -> "A-A12-ramanujan-cube-root"]
VerificationTest[improves[Sqrt[28^(1/3) - 3], (98^(1/3) - 28^(1/3) - 1)/3], True, TestID -> "A-K01-ramanujan-square-root"]
VerificationTest[eq[d[(-1 + 2 I Sqrt[2])^(3/2)], -5 + I Sqrt[2]], True, TestID -> "A-C02-complex-three-halves-power"]
VerificationTest[eq[d[Sqrt[-1 + 2 I Sqrt[2]] Sqrt[-2 + 2 I Sqrt[3]]], (1 + I Sqrt[2]) (1 + I Sqrt[3])], True, TestID -> "A-C03-complex-product"]
VerificationTest[eq[d[-Sqrt[3 + 2 Sqrt[2]]], -1 - Sqrt[2]], True, TestID -> "A-C01-negative-target"]
VerificationTest[Module[{r = d[Sqrt[16 - 2 Sqrt[29] + 2 Sqrt[55 - 10 Sqrt[29]]], True]}, eq[r, Sqrt[5] + Sqrt[11 - 2 Sqrt[29]]] && depth[r] === 2], True, TestID -> "A-A30-bfht-partial-denesting"]
VerificationTest[Module[{r = d[Sqrt[16 - 2 Sqrt[29] + 2 Sqrt[55 - 10 Sqrt[29]]]]}, eq[r, Sqrt[5] + Sqrt[11 - 2 Sqrt[29]]] && depth[r] === 2], True, TestID -> "A-A31-bfht-default-levels"]
VerificationTest[eq[d[Root[#^4 - 10 #^2 + 1 &, 4]], Sqrt[2] + Sqrt[3]], True, TestID -> "A-B07-root-input"]
VerificationTest[d[Sqrt[2 + Sqrt[2]]], Sqrt[2 + Sqrt[2]], TestID -> "A-B01-non-denestable-unchanged"]
VerificationTest[d[(1 + Sqrt[2])^(1/3)], (1 + Sqrt[2])^(1/3), TestID -> "A-B03-non-denestable-cube-root-unchanged"]
VerificationTest[d[Sqrt[z^2]], Sqrt[z^2], TestID -> "A-E01-symbolic-untouched"]
VerificationTest[d[Sqrt[x] Sqrt[3 + 2 Sqrt[2]]], Sqrt[x] (1 + Sqrt[2]), TestID -> "A-E06-numeric-factor-inside-symbolic-product"]
VerificationTest[d[Sqrt[3 + 2 Sqrt[2]] + Pi], 1 + Sqrt[2] + Pi, TestID -> "A-K11-transcendental-host"]
VerificationTest[eq[d[Sqrt[2 + Sqrt[3]] + Sqrt[2 - Sqrt[3]]], Sqrt[6]], True, TestID -> "A-A23-sum-recombined"]
VerificationTest[Module[{r = RadicalDenest3`DenestReport[Sqrt[5 + 2 Sqrt[6]] + Sqrt[1 + Sqrt[2]]]}, r["Status"] === "Improved" && eq[r["Result"], Sqrt[2] + Sqrt[3] + Sqrt[1 + Sqrt[2]]]], True, TestID -> "A-report-status-improved"]
VerificationTest[Module[{r = d[1/(Sqrt[2] + Sqrt[3 + 2 Sqrt[2]])]}, eq[r, (2 Sqrt[2] - 1)/7] && depth[r] === 1], True, TestID -> "A-M02-reciprocal-of-a-sum-island"]
VerificationTest[d[(Sqrt[2 - Sqrt[3]] + Sqrt[2 + Sqrt[3]])^2], 6, TestID -> "A-M15-integer-power-of-a-sum-island"]
VerificationTest[Attributes[Print], {Protected}, TestID -> "A-print-untouched"]

(* ---------------- C: round 3 ---------------- *)
ClearAll[session, memberEq];
SetAttributes[session, HoldAll];
session[body_] := RadicalDenest3`Private`standalone[Block[{RadicalDenest3`Private`$cfg = Join[RadicalDenest3`Private`$cfg, <|"MaxRecursion" -> 0, "MaxTrials" -> 0|>]}, body], $Failed];
memberEq[list_, v_] := ListQ[list] && AnyTrue[list, eq[#, v] &];

(* review-7 *)
VerificationTest[RadicalDenest3`ExactAlgebraicQ /@ {3/7, 2 + 3 I, Pi, 1.2}, {True, True, False, False}, TestID -> "C-R7-admission-basics"]
VerificationTest[RadicalDenest3`ExactAlgebraicQ[Root[#^5 + # - 1 &, 1]], True, TestID -> "C-R7-rational-root-admission"]
VerificationTest[RadicalDenest3`ExactAlgebraicQ[Root[#^5 + # - Pi &, 1]], False, TestID -> "C-R7-transcendental-root-rejected"]
VerificationTest[Module[{a}, RadicalDenest3`ExactAlgebraicQ[Root[#^5 + # + a &, 1]]], False, TestID -> "C-R7-parametric-root-rejected"]
VerificationTest[RadicalDenest3`EqualityStatus[Root[#^5 + # - Pi &, 1], 0], "Unknown", TestID -> "C-R7-unsupported-root-equality-unknown"]
VerificationTest[RadicalDenest3`EqualityStatus[0, 10^-100], "Different", TestID -> "C-R7-small-nonzero-exact"]
VerificationTest[RadicalDenest3`EqualityStatus[(-8)^(1/3), -2], "Different", TestID -> "C-R7-principal-not-real-cube-root"]
VerificationTest[RadicalDenest3`CertifiedEqualQ[Pi, Pi], False, TestID -> "C-R7-outside-grammar-not-certified"]
VerificationTest[Block[{RadicalDenest3`Private`numericallyDifferentQ = (True &)}, RadicalDenest3`EqualityStatus[Sqrt[5 + 2 Sqrt[6]], Sqrt[2] + Sqrt[3]]], "Equal", TestID -> "C-R7-injected-numeric-hint-cannot-decide"]
VerificationTest[FailureQ /@ {RadicalDenest3`Strad[1, 17], RadicalDenest3`Strad[], RadicalDenest3`Strad[1, "Typo" -> 1], RadicalDenest3`Strad[1, "TimeBudget" -> Infinity], RadicalDenest3`Strad[1, "MaxTrials" -> -1], RadicalDenest3`Strad[1, "AllLevels" -> 1], RadicalDenest3`Strad[1, "MaxSolveDegree" -> 5]}, ConstantArray[True, 7], TestID -> "C-R7-malformed-and-invalid-options-fail"]
VerificationTest[FailureQ /@ {RadicalDenest3`DenestRadicals[], RadicalDenest3`DenestCore[], RadicalDenest3`DenestReport[], RadicalDenest3`DenestReport[1, 2, 3]}, {True, True, True, True}, TestID -> "C-R7-every-entry-point-rejects-malformed-calls"]
VerificationTest[RadicalDenest3`DenestReport[Sqrt[5 + 2 Sqrt[6]], "TimeBudget" -> 0]["Status"], "Disabled", TestID -> "C-R7-zero-budget-disabled"]
VerificationTest[RadicalDenest3`DenestReport[1, "TimeBudget" -> 0][[{"InitialCost", "FinalCost"}]], <|"InitialCost" -> Missing["NotComputed"], "FinalCost" -> Missing["NotComputed"]|>, TestID -> "C-R7-disabled-no-unbudgeted-cost"]
VerificationTest[RadicalDenest3`DenestReport[1, {"MaxTrials" -> 0}, "TimeBudget" -> 0]["Options"]["MaxTrials"], 0, TestID -> "C-R7-nested-option-list"]
VerificationTest[RadicalDenest3`DenestReport[1, "MaxTrials" -> 0, "MaxTrials" -> 3]["Options"]["MaxTrials"], 0, TestID -> "C-R7-first-option-wins"]
VerificationTest[Module[{old = Options[RadicalDenest3`Strad], r}, SetOptions[RadicalDenest3`Strad, "TimeBudget" -> 0]; r = RadicalDenest3`Strad[Sqrt[5 + 2 Sqrt[6]]]; Options[RadicalDenest3`Strad] = old; r], Sqrt[5 + 2 Sqrt[6]], TestID -> "C-R7-setoptions-entrypoint"]
VerificationTest[{RadicalDenest3`RadicalDepth[Sqrt[1 + Sqrt[2]]], RadicalDenest3`RadicalDepth[Root[#^5 + Sqrt[2] # + 1 &, 1]], RadicalDenest3`RadicalCost[Root[#^5 + Sqrt[2] # + 1 &, 1]][[3]]}, {2, 0, 0}, TestID -> "C-R7-opaque-depth-and-radical-count"]
VerificationTest[RadicalDenest3`RadicalCost[1 + 2^100 I][[5]] > RadicalDenest3`RadicalCost[1 + I][[5]], True, TestID -> "C-R7-complex-bit-size"]
VerificationTest[improves[(41 - 29 Sqrt[2])^(1/5), (-1)^(1/5) (Sqrt[2] - 1)], True, TestID -> "C-R7-negative-fifth-root"]
VerificationTest[improves[(239 + 169 Sqrt[2])^(1/7), 1 + Sqrt[2]], True, TestID -> "C-R7-higher-odd-seventh"]
VerificationTest[session[Module[{z = 1 + Sqrt[2], rho}, rho = Expand[z^9]; AnyTrue[RadicalDenest3`Private`quadraticOddRoots[RadicalDenest3`Private`quadraticParts[rho], 9], eq[#, z] &]]], True, TestID -> "C-R7-higher-odd-ninth-private-recipe"]
VerificationTest[Module[{e = Sqrt[15 + 2 Sqrt[6] + 2 Sqrt[10] + 2 Sqrt[15]]}, eq[d[e], e]], True, TestID -> "C-R7-multisurd-safety"]
VerificationTest[Module[{e = x + Sqrt[1 + Sqrt[2]], r}, r = Block[{$Assumptions = x == 0}, d[e, "Solver" -> (0 &), "MaxTrials" -> 0]]; ! FreeQ[r, x] && eq[(r - x) - (e - x), 0]], True, TestID -> "C-R7-assumptions-isolation"]
VerificationTest[Module[{e = 1.0 + Sqrt[1 + Sqrt[2]]}, d[e] === e], True, TestID -> "C-R7-inexact-tree-noop"]
VerificationTest[d[HoldComplete[Sqrt[5 + 2 Sqrt[6]]]], HoldComplete[Sqrt[5 + 2 Sqrt[6]]], TestID -> "C-R7-held-host-opaque"]
VerificationTest[Module[{e = Sqrt[1 + Sqrt[2]], r}, r = RadicalDenest3`DenestReport[e, "MaxTrials" -> 0, "Multipliers" -> {}, "Solver" -> (0 &)]; eq[r["Result"], e] && r["Statistics"]["Trials"] === 0], True, TestID -> "C-R7-zero-trials-safe"]
VerificationTest[Module[{e = Sqrt[1 + Sqrt[2]], r}, r = RadicalDenest3`DenestReport[e, "MaxTrials" -> 1, "MultiplierCap" -> 1, "MaxRecursion" -> 0]; eq[r["Result"], e] && r["Statistics"]["Trials"] <= 1], True, TestID -> "C-R7-single-visit-trial-cap"]
VerificationTest[Module[{e = Sqrt[1 + Sqrt[2]], r}, r = RadicalDenest3`DenestReport[e, "Solver" -> (Throw[0] &), "MaxTrials" -> 0]; eq[r["Result"], e]], True, TestID -> "C-R7-throwing-solver-quarantined"]
VerificationTest[Module[{e = Sqrt[5 + 2 Sqrt[6]], r}, r = RadicalDenest3`DenestReport[e]; r["FinalCost"] === RadicalDenest3`RadicalCost[r["Result"]] && StringQ[r["CertificateKind"]] && r["ResultChanged"] === True && r["CertificatesTruncated"] === False], True, TestID -> "C-R7-report-cost-and-evidence-kind"]
VerificationTest[session[Module[{t = (3 + 2 Sqrt[2])^(1/4), i = Sqrt[1 + Sqrt[2]]}, RadicalDenest3`Private`negativeRadicandCandidate[t, 3 + 2 Sqrt[2], 1, 4, i] === i]], True, TestID -> "C-R7-positive-radicand-preserves-incumbent"]
VerificationTest[session[Block[{RadicalDenest3`Private`linearRoots = Function[{r, k}, {}], RadicalDenest3`Private`recurse = Identity}, Module[{t = (3 + 2 Sqrt[2])^(1/4), i = Sqrt[1 + Sqrt[2]], r}, r = RadicalDenest3`Private`powerProposals[t, i]; eq[r, t] && RadicalDenest3`Private`cheaperQ[r, t]]]], True, TestID -> "C-R7-power-stage-monotonicity-mocked-search"]
VerificationTest[session[Block[{RadicalDenest3`Private`linearRoots = Function[{r, k}, If[k === 2, {1 + Sqrt[2]}, {}]], RadicalDenest3`Private`recurse = Identity}, Module[{t = (3 + 2 Sqrt[2])^(1/4), r}, r = RadicalDenest3`Private`kummerCandidates[t, 3 + 2 Sqrt[2], 1, 4, t]; eq[r, t] && RadicalDenest3`Private`cheaperQ[r, t]]]], True, TestID -> "C-R7-unchanged-subproblem-admitted-mocked-factors"]

(* review-8 *)
VerificationTest[RadicalDenest3`ExactAlgebraicQ /@ {3/7 + I/5, Root[#^5 - # - 1 &, 1], Root[#^3 + Pi # + 1 &, 1], Root[#^3 - # + parameter &, 1], Root[#^3 + Sqrt[2] # + 1 &, 1], AlgebraicNumber[Sqrt[2], {1, 2}], Pi, 1.0, Infinity}, {True, True, False, False, True, True, False, False, False}, TestID -> "C-R8-grammar"]
VerificationTest[RadicalDenest3`RadicalExpressionQ[Root[#^5 - # - 1 &, 1]], False, TestID -> "C-R8-opaque-not-output"]
VerificationTest[RadicalDenest3`EqualityStatus @@@ {{Sqrt[5 + 2 Sqrt[6]], Sqrt[2] + Sqrt[3]}, {Sqrt[2], -Sqrt[2]}, {1, 1 + 10^-1000}, {Pi, Pi}}, {"Equal", "Different", "Different", "Unknown"}, TestID -> "C-R8-equality-status"]
VerificationTest[Module[{e = Sqrt[3/2 + Sqrt[3]], r}, r = d[e]; eq[r, e] && depth[r] < depth[e]], True, TestID -> "C-R8-indirect-rational"]
VerificationTest[improves[(-239 - 169 Sqrt[2])^(1/7), (-1)^(1/7) (1 + Sqrt[2])], True, TestID -> "C-R8-negative-seventh"]
VerificationTest[improves[(1393 - 985 Sqrt[2])^(1/9), (-1)^(1/9) (Sqrt[2] - 1)], True, TestID -> "C-R8-negative-ninth"]
VerificationTest[session[RadicalDenest3`Private`negativeRadicandCandidate[(3 + 2 Sqrt[2])^(1/6), 3 + 2 Sqrt[2], 1, 6, (1 + Sqrt[2])^(1/3)]] === (1 + Sqrt[2])^(1/3), True, TestID -> "C-R8-negative-stage-preserves-incumbent"]
VerificationTest[Module[{t = (3 + 2 Sqrt[2])^(1/6), r}, r = session[RadicalDenest3`Private`kummerCandidates[t, 3 + 2 Sqrt[2], 1, 6, t]]; {eq[r, t], RadicalDenest3`Private`cheaperQ[r, t]}], {True, True}, TestID -> "C-R8-raw-index-reduction-without-recursion"]
VerificationTest[memberEq[session[RadicalDenest3`Private`honsbeekSquareRoots[28^(1/3) - 3]], Sqrt[28^(1/3) - 3]], True, TestID -> "C-R8-honsbeek-rational-summand"]
VerificationTest[memberEq[session[RadicalDenest3`Private`honsbeekSquareRoots[5^(1/3) - 4^(1/3)]], Sqrt[5^(1/3) - 4^(1/3)]], True, TestID -> "C-R8-honsbeek-classical"]
VerificationTest[MemberQ[session[RadicalDenest3`Private`cosetBases[{55, 210, 462}, {2, 3, 5, 7, 11}]], {6, 35, 77, 330}], True, TestID -> "C-R8-coset-enumeration"]
VerificationTest[memberEq[session[RadicalDenest3`Private`surdSystem[{6, 35, 77, 330}, <|1 -> 118, 55 -> 14, 210 -> 2, 462 -> 2|>]], Sqrt[6] + Sqrt[35] + Sqrt[77]], True, TestID -> "C-R8-coset-coefficient-solver"]
VerificationTest[memberEq[session[RadicalDenest3`Private`surdRelation[{6, 35, 77, 330}, 118 + 2 Sqrt[210] + 14 Sqrt[55] + 2 Sqrt[462]]], Sqrt[6] + Sqrt[35] + Sqrt[77]], True, TestID -> "C-R8-coset-integer-relation"]
VerificationTest[RadicalDenest3`Private`radicalNodes[AlgebraicNumber[Root[#^5 + Sqrt[2] # + 1 &, 1], {1, 1}]], 0, TestID -> "C-R8-opaque-node-count"]
VerificationTest[eq[RadicalDenest3`RationalizeDenominator[1/(2 + I)], 1/(2 + I)], True, TestID -> "C-R8-gaussian-denominator"]
VerificationTest[{d[1.0 + symbolic] === 1.0 + symbolic, d[{1.0, Sqrt[5 + 2 Sqrt[6]]}] === {1.0, Sqrt[5 + 2 Sqrt[6]]}, d[f[Sqrt[5 + 2 Sqrt[6]]]] === f[Sqrt[5 + 2 Sqrt[6]]]}, {True, True, True}, TestID -> "C-R8-inexact-and-unknown-heads-untouched"]
VerificationTest[FailureQ /@ {d[Sqrt[3 + 2 Sqrt[2]], "MultiplierCap" -> Infinity], d[Sqrt[3 + 2 Sqrt[2]], "MaxOddIndex" -> 0], d[Sqrt[3 + 2 Sqrt[2]], "MaxCosets" -> -1], d[Sqrt[3 + 2 Sqrt[2]], "DiscriminantBatchCap" -> 1/2]}, {True, True, True, True}, TestID -> "C-R8-new-options-validated"]
VerificationTest[Module[{r = RadicalDenest3`DenestReport[Sqrt[3 + 2 Sqrt[2]], "MaxTraceEntries" -> 0]}, {StringQ[r["CertificateKind"]], r["Certificates"], r["CertificatesTruncated"], r["CompletenessClaim"]}], {True, {}, True, False}, TestID -> "C-R8-report-scopes"]
VerificationTest[session[Block[{RadicalDenest3`Private`powerProposals = Function[{target, best}, best], RadicalDenest3`Private`genericProposals = Function[{target, best}, best], RadicalDenest3`Private`multiplierSearch = Function[{target, best}, best]}, RadicalDenest3`Private`improveNumber[Sqrt[2 + Sqrt[2]]]; RadicalDenest3`Private`$memo[Sqrt[2 + Sqrt[2]]][[{"Result", "Complete"}]]]], <|"Result" -> Sqrt[2 + Sqrt[2]], "Complete" -> True|>, TestID -> "C-R8-failed-search-cached-with-budget"]

(* review-9 *)
VerificationTest[RadicalDenest3`ExactAlgebraicQ[AlgebraicNumber[Root[#^3 - # - 1 &, 1], {1, 2, 3}]], True, TestID -> "C-R9-domain-algebraic-number"]
VerificationTest[RadicalDenest3`EqualityStatus[Sqrt[3 + 2 Sqrt[2]], -1 - Sqrt[2]], "Different", TestID -> "C-R9-equality-wrong-branch"]
VerificationTest[RadicalDenest3`Private`bitSize[1 + I] > 0, True, TestID -> "C-R9-cost-gaussian-bits"]
VerificationTest[FailureQ /@ {RadicalDenest3`DenestCore[Sqrt[2], "MaxTrials" -> -1], RadicalDenest3`DenestReport[Sqrt[2], "MaxCosets" -> 5/2], RadicalDenest3`Strad[Sqrt[2], 123]}, {True, True, True}, TestID -> "C-R9-option-failures"]
VerificationTest[MissingQ[RadicalDenest3`DenestReport[Sqrt[2], "TimeBudget" -> 0]["InitialCost"]], True, TestID -> "C-R9-zero-budget-no-post-cost"]
VerificationTest[RadicalDenest3`DenestCore[Sqrt[3 + 2 Sqrt[2]], "MaxTrials" -> 0], 1 + Sqrt[2], TestID -> "C-R9-direct-quadratic"]
VerificationTest[RadicalDenest3`DenestCore[Sqrt[3 - 2 Sqrt[2]], "MaxTrials" -> 0], Sqrt[2] - 1, TestID -> "C-R9-quadratic-negative-coefficient"]
VerificationTest[eq[RadicalDenest3`DenestCore[(-7 - 5 Sqrt[2])^(1/3), "MaxTrials" -> 0], (-1)^(1/3) (1 + Sqrt[2])], True, TestID -> "C-R9-principal-negative-cube"]
VerificationTest[eq[RadicalDenest3`DenestCore[(41 + 29 Sqrt[2])^(1/5), "MaxTrials" -> 0], 1 + Sqrt[2]], True, TestID -> "C-R9-fifth-root-Dickson"]
VerificationTest[Module[{r = RadicalDenest3`DenestCore[Sqrt[37 + 4 Sqrt[15] + 6 Sqrt[14] + 2 Sqrt[210]], "MaxTrials" -> 0]}, eq[r, Sqrt[6] + Sqrt[10] + Sqrt[21]] && depth[r] === 1], True, TestID -> "C-R9-character-missing-coset"]
VerificationTest[d[x + Sqrt[3 + 2 Sqrt[2]], "MaxTrials" -> 0], x + 1 + Sqrt[2], TestID -> "C-R9-symbolic-host-congruence"]
VerificationTest[Module[{calls = 0, target = Sqrt[2 + Sqrt[2]], result}, result = RadicalDenest3`DenestCore[target, "Solver" -> Function[e, calls++; 0], "MaxTrials" -> 0]; calls > 0 && result =!= 0 && eq[result, target]], True, TestID -> "C-R9-incorrect-callback-cannot-override"]
VerificationTest[RadicalDenest3`Private`standalone[Block[{RadicalDenest3`Private`recurse = Function[e, e]}, RadicalDenest3`Private`kummerCandidates[(3 + 2 Sqrt[2])^(1/4), 3 + 2 Sqrt[2], 1, 4]], $Failed], Sqrt[1 + Sqrt[2]], TestID -> "C-R9-index-reduction-without-recursive-progress"]
VerificationTest[RadicalDenest3`Private`standalone[Module[{target = (-7 - 5 Sqrt[2])^(1/3), partial = 1 + Sqrt[2], r}, Block[{RadicalDenest3`Private`rootCandidates = Function[{rr, q}, {}], RadicalDenest3`Private`recurse = Function[e, partial], RadicalDenest3`Private`linearRoots = Function[{rr, q}, {}]}, r = RadicalDenest3`Private`powerProposals[target, target]]; eq[r, (-1)^(1/3) partial] && depth[r] === 1], $Failed], True, TestID -> "C-R9-partial-negative-improvement-survives-later-noop"]
VerificationTest[RadicalDenest3`Private`standalone[Module[{calls = 0, target = Sqrt[2 + Sqrt[2]]}, Block[{RadicalDenest3`Private`powerProposals = Function[{t, b}, b], RadicalDenest3`Private`genericProposals = Function[{t, b}, b], RadicalDenest3`Private`multiplierSearch = Function[{t, b}, calls++; b]}, Block[{RadicalDenest3`Private`$recursion = 1}, RadicalDenest3`Private`improveNumber[target]]; RadicalDenest3`Private`improveNumber[target]; RadicalDenest3`Private`improveNumber[target]; calls]], $Failed], 2, TestID -> "C-R9-weak-negative-result-not-reused-by-stronger-search"]
VerificationTest[RadicalDenest3`Private`standalone[Module[{target = Sqrt[2 + Sqrt[2]]}, AssociateTo[RadicalDenest3`Private`$inProgress, target -> True]; RadicalDenest3`Private`improveNumber[target] === target], $Failed], True, TestID -> "C-R9-in-progress-cycle-cut"]
VerificationTest[RadicalDenest3`Private`standalone[Block[{RadicalDenest3`Private`$cfg = Append[RadicalDenest3`Private`$cfg, "NumericPrefilter" -> True], RadicalDenest3`Private`numericallyDifferentQ = Function[e, True]}, RadicalDenest3`Private`certify[Sqrt[3 + 2 Sqrt[2]], 1 + Sqrt[2]]], $Failed], "Equal", TestID -> "C-R9-numeric-diagnostic-never-suppresses-exact-proof"]
VerificationTest[Module[{rep = RadicalDenest3`DenestReport[Sqrt[3 + 2 Sqrt[2]], "MaxTrials" -> 0]}, AllTrue[rep["Certificates"], RadicalDenest3`CertifiedEqualQ[#["Before"], #["After"]] && StringQ[#["EqualityMethod"]] &]], True, TestID -> "C-R9-every-reported-proposal-recertifies"]

(* unified-C controls *)
VerificationTest[improves[Sqrt[118 + 2 Sqrt[210] + 14 Sqrt[55] + 2 Sqrt[462]], Sqrt[6] + Sqrt[35] + Sqrt[77], "MaxTrials" -> 0], True, TestID -> "C-U-coset-1"]
VerificationTest[improves[Sqrt[60 + 10 Sqrt[6] + 10 Sqrt[14] + 10 Sqrt[21]], Sqrt[10] + Sqrt[15] + Sqrt[35], "MaxTrials" -> 0], True, TestID -> "C-U-coset-2"]
VerificationTest[improves[Sqrt[142 + 28 Sqrt[15] + 20 Sqrt[21] + 12 Sqrt[35]], Sqrt[30] + Sqrt[42] + Sqrt[70], "MaxTrials" -> 0], True, TestID -> "C-U-coset-3"]
VerificationTest[improves[Sqrt[(5 + Sqrt[6] + Sqrt[10] + Sqrt[15])/2], (Sqrt[2] + Sqrt[3] + Sqrt[5])/2, "MaxTrials" -> 0], True, TestID -> "C-U-coset-rational-coefficients"]
VerificationTest[improves[Sqrt[280 + 16 Sqrt[6] - 48 Sqrt[10] - 32 Sqrt[15]], -4 - 2 Sqrt[6] + 4 Sqrt[15], "MaxTrials" -> 0], True, TestID -> "C-U-coset-negative-coefficients"]
VerificationTest[Module[{r = RadicalDenest3`DenestReport[(3 + 2 Sqrt[2])^(1/6), "MaxRecursion" -> 0]}, eq[r["Result"], (1 + Sqrt[2])^(1/3)] && MemberQ[r["Limits"], "Patience"] && r["Statistics"]["Trials"] <= r["Options"]["Patience"] + 1], True, TestID -> "C-U-patience-counts-from-earlier-improvement"]
VerificationTest[Module[{r = RadicalDenest3`DenestReport[Sqrt[54 - 4 Sqrt[33] + 4 Sqrt[39] - 4 Sqrt[143]], "MaxTrials" -> 0]}, eq[r["Result"], Sqrt[6] - Sqrt[22] + Sqrt[26]] && r["Statistics"]["CosetSystems"] === 0 && r["Statistics"]["FastPathAccepted"] === 1], True, TestID -> "C-U-coset-relation-stage-suffices"]
VerificationTest[Module[{e = (3 + 2 Sqrt[2])^(1/4), r}, r = d[e]; eq[r, Sqrt[1 + Sqrt[2]]] && RadicalDenest3`Private`cheaperQ[r, e]], True, TestID -> "C-U-quartic-index-reduction"]
VerificationTest[Module[{e = (3 + 2 Sqrt[2])^(1/6), r}, r = d[e, "MaxRecursion" -> 0]; eq[r, (1 + Sqrt[2])^(1/3)] && RadicalDenest3`Private`cheaperQ[r, e]], True, TestID -> "C-U-sixth-index-reduction-no-recursion"]
VerificationTest[Module[{e = Expand[(1 + Sqrt[5])^11]^(1/11)}, {session[RadicalDenest3`Private`rootCandidates[First[e], 11]], eq[d[e, "MaxTrials" -> 0], 1 + Sqrt[5]], memberEq[session[Block[{RadicalDenest3`Private`$cfg = Append[RadicalDenest3`Private`$cfg, "MaxOddIndex" -> 11]}, RadicalDenest3`Private`rootCandidates[First[e], 11]]], 1 + Sqrt[5]]}], {{}, True, True}, TestID -> "C-U-max-odd-index"]
VerificationTest[d[Sqrt[2], "NumericPrefilter" -> True] === Sqrt[2] && improves[Sqrt[5 + 2 Sqrt[6]], Sqrt[2] + Sqrt[3], "NumericPrefilter" -> True], True, TestID -> "C-U-prefilter-is-optional-pruning"]
VerificationTest[Module[{r = RadicalDenest3`DenestReport[Sqrt[1 + Sqrt[2]], "MaxTrials" -> 2, "NumericPrefilter" -> False]["Statistics"]}, r["NumericRejections"] === 0 && r["Certificates"] === r["CertificatesEqual"] + r["CertificatesDifferent"] + r["CertificatesUnknown"]], True, TestID -> "C-U-certificate-counters-exact-only"]
VerificationTest[d[Root[#^5 + # - Pi &, 1] + Sqrt[5 + 2 Sqrt[6]]], Root[#^5 + # - Pi &, 1] + Sqrt[2] + Sqrt[3], TestID -> "C-U-unsupported-root-is-an-opaque-host"]
VerificationTest[RadicalDenest3`RadicalCost[Sqrt[2] + Root[#^5 + # - 1 &, 1]] === {1, 1, 1, LeafCount[Sqrt[2] + Root[#^5 + # - 1 &, 1]], RadicalDenest3`Private`bitSize[Sqrt[2] + Root[#^5 + # - 1 &, 1]]}, True, TestID -> "C-U-cost-recursive-counters"]
VerificationTest[Module[{r = RadicalDenest3`DenestReport[Sqrt[5 + 2 Sqrt[6]] + N[Pi]]}, {r["Status"], r["Limits"], r["InitialCost"]}], {"Unchanged", {"InexactInput"}, Missing["NotComputed"]}, TestID -> "C-U-inexact-input-classified-inside-region"]
VerificationTest[Module[{r = RadicalDenest3`DenestReport[Sqrt[1 + Sqrt[2]], "MaxTrials" -> 0]}, {r["ResultChanged"], r["Status"], r["InitialCost"] === r["FinalCost"]}], {False, "Unchanged", True}, TestID -> "C-U-unchanged-report"]
VerificationTest[improves[Sqrt[-(16 - 2 Sqrt[29] + 2 Sqrt[55 - 10 Sqrt[29]])], I (Sqrt[5] + Sqrt[11 - 2 Sqrt[29]])], True, TestID -> "C-U-negative-radicand-partial-denesting"]

End[];
