(* The round-3 reviews' never-executed probes, run against the SECOND corrected
   version StradFixed2.wl (the version they reviewed). *)
Get["C:/RadicalDenest/.claude/worktrees/strad-denesting-analysis-6158e6/src/corrected/StradFixed2.wl"];
Print["Kernel: ", $Version];
SetAttributes[tc, HoldAll];
tc[e_] := TimeConstrained[e, 120, $Aborted];
SetAttributes[show, HoldRest];
show[label_, e_] := Module[{t, r}, {t, r} = AbsoluteTiming[tc[e]]; Print[label, ": ", InputForm[r], "   [", Round[t, 0.01], " s]"]];
Print["--- grammar (R7 F01, R8 F01, R9 F1) ---"];
show["ExactAlgebraicQ[Root[#^5 + # - Pi &, 1]]", RadicalDenest2`ExactAlgebraicQ[Root[#^5 + # - Pi &, 1]]];
show["ExactAlgebraicQ[Root[#^3 - # + parameter &, 1]]", RadicalDenest2`ExactAlgebraicQ[Root[#^3 - # + parameter &, 1]]];
show["ExactAlgebraicQ[AlgebraicNumber[Pi, {1, 1}]]", RadicalDenest2`ExactAlgebraicQ[AlgebraicNumber[Pi, {1, 1}]]];
show["Strad[Root[#^5 + # - Pi &, 1] + Sqrt[5 + 2 Sqrt[6]]]", RadicalDenest2`Strad[Root[#^5 + # - Pi &, 1] + Sqrt[5 + 2 Sqrt[6]]]];
Print["--- numeric prefilter decides EqualityStatus (R7 F02, R8 F02, R9 F2) ---"];
show["EqualityStatus[Sqrt[2], -Sqrt[2]]", RadicalDenest2`EqualityStatus[Sqrt[2], -Sqrt[2]]];
show["EqualityStatus with numericallyDifferentQ forced True", Block[{RadicalDenest2`Private`numericallyDifferentQ = (True &)}, RadicalDenest2`EqualityStatus[Sqrt[5 + 2 Sqrt[6]], Sqrt[2] + Sqrt[3]]]];
show["NumericRejections counted as CertificatesDifferent", RadicalDenest2`DenestReport[Sqrt[1 + Sqrt[2]], "MaxTrials" -> 3]["Statistics"][[{"Certificates", "CertificatesDifferent", "NumericRejections"}]]];
Print["--- incumbent reset in powerProposals (R7 F03, R8 F03, R9 F3) ---"];
target = (3 + 2 Sqrt[2])^(1/6); incumbent = (1 + Sqrt[2])^(1/3);
show["RootReduce[target - incumbent] === 0", RootReduce[target - incumbent] === 0];
show["powerProposals[target, incumbent] with MaxRecursion 0, MaxTrials 0", RadicalDenest2`Private`standalone[Block[{RadicalDenest2`Private`$cfg = Join[RadicalDenest2`Private`$cfg, <|"MaxRecursion" -> 0, "MaxTrials" -> 0|>]}, RadicalDenest2`Private`powerProposals[target, incumbent]], $Failed]];
show["kummerCandidates[(3+2Sqrt[2])^(1/4), rho, 1, 4] with recurse = Identity", RadicalDenest2`Private`standalone[Block[{RadicalDenest2`Private`recurse = Identity}, RadicalDenest2`Private`kummerCandidates[(3 + 2 Sqrt[2])^(1/4), 3 + 2 Sqrt[2], 1, 4]], $Failed]];
show["Strad[(3 + 2 Sqrt[2])^(1/6), MaxRecursion -> 0]", RadicalDenest2`Strad[(3 + 2 Sqrt[2])^(1/6), "MaxRecursion" -> 0]];
show["Strad[(3 + 2 Sqrt[2])^(1/6)]", RadicalDenest2`Strad[(3 + 2 Sqrt[2])^(1/6)]];
show["Strad[(3 + 2 Sqrt[2])^(1/4)]", RadicalDenest2`Strad[(3 + 2 Sqrt[2])^(1/4)]];
Print["--- negative memo (R7 F05, R8 F05, R9 F5) ---"];
show["memo entry after a failed search", RadicalDenest2`Private`standalone[Block[{RadicalDenest2`Private`$cfg = Join[RadicalDenest2`Private`$cfg, <|"MaxRecursion" -> 0, "MaxTrials" -> 0|>]}, RadicalDenest2`Private`improveNumber[Sqrt[1 + Sqrt[2]]]; KeyExistsQ[RadicalDenest2`Private`$memo, Sqrt[1 + Sqrt[2]]]], $Failed]];
Print["--- malformed calls (R7 F08, R8 F09, R9 F8) ---"];
show["Strad[Sqrt[2], 17]", RadicalDenest2`Strad[Sqrt[2], 17]];
show["Strad[]", RadicalDenest2`Strad[]];
show["DenestReport[1, TimeBudget -> 0][InitialCost]", RadicalDenest2`DenestReport[1, "TimeBudget" -> 0]["InitialCost"]];
Print["--- cost (R7 F09, R9 F7) ---"];
show["RadicalCost[1 + 2^100 I] vs RadicalCost[1 + I]", {RadicalDenest2`RadicalCost[1 + 2^100 I], RadicalDenest2`RadicalCost[1 + I]}];
show["radicalNodes[AlgebraicNumber[Root[#^5 + Sqrt[2] # + 1 &, 1], {1, 1}]]", RadicalDenest2`Private`radicalNodes[AlgebraicNumber[Root[#^5 + Sqrt[2] # + 1 &, 1], {1, 1}]]];
Print["--- coverage: cosets (R8 F06, R9 F9), odd indices (R7 F12, R8 F07), Honsbeek (R8 F08) ---"];
show["Strad[Sqrt[118 + 2 Sqrt[210] + 14 Sqrt[55] + 2 Sqrt[462]], MaxTrials -> 0]", RadicalDenest2`Strad[Sqrt[118 + 2 Sqrt[210] + 14 Sqrt[55] + 2 Sqrt[462]], "MaxTrials" -> 0]];
show["Strad[Sqrt[118 + 2 Sqrt[210] + 14 Sqrt[55] + 2 Sqrt[462]]]", RadicalDenest2`Strad[Sqrt[118 + 2 Sqrt[210] + 14 Sqrt[55] + 2 Sqrt[462]]]];
show["Strad[Sqrt[37 + 4 Sqrt[15] + 6 Sqrt[14] + 2 Sqrt[210]], MaxTrials -> 0]", RadicalDenest2`Strad[Sqrt[37 + 4 Sqrt[15] + 6 Sqrt[14] + 2 Sqrt[210]], "MaxTrials" -> 0]];
show["Strad[Sqrt[142 + 28 Sqrt[15] + 20 Sqrt[21] + 12 Sqrt[35]]]", RadicalDenest2`Strad[Sqrt[142 + 28 Sqrt[15] + 20 Sqrt[21] + 12 Sqrt[35]]]];
show["Strad[(41 + 29 Sqrt[2])^(1/5), MaxTrials -> 0]", RadicalDenest2`Strad[(41 + 29 Sqrt[2])^(1/5), "MaxTrials" -> 0]];
show["Strad[(41 + 29 Sqrt[2])^(1/5)]", RadicalDenest2`Strad[(41 + 29 Sqrt[2])^(1/5)]];
show["Strad[(239 + 169 Sqrt[2])^(1/7)]", RadicalDenest2`Strad[(239 + 169 Sqrt[2])^(1/7)]];
show["Strad[(1393 - 985 Sqrt[2])^(1/9)]", RadicalDenest2`Strad[(1393 - 985 Sqrt[2])^(1/9)]];
show["Strad[Sqrt[28^(1/3) - 3]]", RadicalDenest2`Strad[Sqrt[28^(1/3) - 3]]];
Print["DONE"];
